
/**
 * This file is part of CamusDB
 *
 * For the full copyright and license information, please view the LICENSE.txt
 * file that was distributed with this source code.
 */

namespace CamusDB.Core.SQLParser;

public enum NodeType
{
    Integer,
    Float,
    String,
    Bool,
    Null,
    ObjectIdLiteral,
    Identifier,
    IdentifierList,
    IdentifierWithOpts,
    Placeholder,
    ExprList,
    ExprEquals,
    ExprNotEquals,
    ExprLessThan,
    ExprGreaterThan,
    ExprGreaterEqualsThan,
    ExprLessEqualsThan,
    ExprBetween,
    ExprOr,
    ExprAnd,
    ExprNot,
    ExprAdd,
    ExprSub,
    ExprMult,
    ExprAllFields,
    ExprFuncCall,
    ExprCast,
    ExprArgumentList,
    ExprAlias,
    ExprLike,
    ExprILike,
    ExprDefault,
    ExprIsNull,
    ExprIsNotNull,
    ExprScalarSubquery,
    ExprInSubquery,
    ExprInMembership,
    ExprNotInSubquery,
    ExprNotInMembership,
    ExprExistsCorrelated,
    ExprExistsSubquery,
    Select,
    GroupBy,
    Having,
    TableReference,
    DerivedTableReference,
    CommaJoin,
    CommaJoinTableList,
    Join,
    Update,
    UpdateList,
    UpdateItem,
    Delete,
    Insert,
    InsertBatchList,
    Begin,
    Commit,
    Rollback,
    SetTransaction,
    SortAsc,
    SortDesc,
    CreateTable,
    CreateTableIfNotExists,
    CreateTableItem,
    CreateTableItemList,
    CreateTableFieldConstraintList,
    CreateTableConstraintList,
    CreateTableConstraintPrimaryKey,
    CreateTableConstraintMultiIndex,
    CreateTableConstraintUniqueIndex,
    ConstraintNull,
    ConstraintNotNull,
    ConstraintPrimaryKey,
    ConstraintUnique,
    ConstraintDefault,
    DropTable,
    DropTableIfExists,
    AlterTableAddColumn,
    AlterTableDropColumn,
    AlterTableAddIndex,
    AlterTableAddIndexIfNotExists,
    AlterTableAddUniqueIndex,
    AlterTableAddUniqueIndexIfNotExists,
    AlterTableDropIndex,
    AlterTableAddPrimaryKey,
    AlterTableDropPrimaryKey,
    AlterTableRenameTo,
    AlterTableRenameColumn,
    AlterTableRenameIndex,
    IndexIdentifierList,
    IndexIdentifierAsc,
    IndexIdentifierDesc,
    TypeObjectId,
    TypeString,
    TypeStringSized,
    TypeInteger64,
    TypeFloat64,
    TypeBool,
    TypeFloat32,
    TypeBytes,
    TypeDate,
    TypeDateTime,
    TypeArray,
    ShowColumns,
    ShowTables,
    ShowCreateTable,
    ShowDatabase,
    ShowDatabases,
    ShowBranches,
    ShowAncestors,
    CreateDatabase,
    CreateDatabaseIfNotExists,
    CreateDatabaseBranch,
    CreateDatabaseBranchIfNotExists,
    DropDatabase,
    DropDatabaseIfExists,
    RenameDatabase,
    ShowIndexes,
    Explain,
    ExplainLogical,
    ExplainPhysical,
    ExplainAnalyze,
    AnalyzeTable,
    /// <summary>
    /// Cache hint extracted from a <c>{cache=name}</c> table-reference hint.
    /// Layout: <c>yytext</c> = cache name; <c>leftAst</c> = option list (ExprList of
    /// String/Integer option nodes) or single option node; null when no options.
    /// Option nodes: NodeType.String with yytext="strict"; NodeType.Integer with yytext=ttl_ms.
    /// </summary>
    CacheHint,
}
