
/**
 * This file is part of CamusDB
 *
 * For the full copyright and license information, please view the LICENSE.txt
 * file that was distributed with this source code.
 */

namespace CamusDB.Core.SQLParser;

public enum NodeType
{
    Number,
    String,
    Bool,
    Null,
    Identifier,
    IdentifierList,
    IdentifierWithOpts,
    Placeholder,
    ExprList,
    ExprEquals,
    ExprNotEquals,
    ExprLessThan,
    ExprGreaterThan,
    ExprGreaterEqualsThan,
    ExprLessEqualsThan,
    ExprOr,
    ExprAnd,
    ExprAdd,
    ExprSub,
    ExprMult,
    ExprAllFields,
    ExprFuncCall,
    ExprArgumentList,
    ExprAlias,
    ExprLike,
    ExprILike,
    ExprDefault,
    ExprIsNull,
    ExprIsNotNull,
    Select,
    Update,
    UpdateList,
    UpdateItem,
    Delete,
    Insert,
    SortAsc,
    SortDesc,
    CreateTable,
    CreateTableIfNotExists,
    CreateTableItem,
    CreateTableItemList,
    CreateTableFieldConstraintList,
    CreateTableConstraintList,
    CreateTableConstraintPrimaryKey,
    ConstraintNull,
    ConstraintNotNull,
    ConstraintPrimaryKey,
    ConstraintUnique,
    ConstraintDefault,
    DropTable,
    AlterTableAddColumn,
    AlterTableDropColumn,
    AlterTableAddIndex,
    AlterTableAddUniqueIndex,
    AlterTableDropIndex,
    AlterTableAddPrimaryKey,
    AlterTableDropPrimaryKey,
    IndexIdentifierList,
    IndexIdentifierAsc,
    IndexIdentifierDesc,
    TypeObjectId,
    TypeString,
    TypeInteger64,
    TypeFloat64,
    TypeBool,
    ShowColumns,
    ShowTables,
    ShowCreateTable,
    ShowDatabase,
    ShowIndexes
}
