// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, John Gough, QUT 2005-2014
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.5.2
// DateTime: 12/29/2023 3:06:40 PM
// Input file <SQLParser/SQLParser.Language.grammar.y - 12/29/2023 3:06:36 PM>

// options: no-lines gplex

using System;
using System.Collections.Generic;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Text;
using QUT.Gppg;

namespace CamusDB.Core.SQLParser
{
internal enum Token {error=2,EOF=3,TOR=4,TAND=5,TEQUALS=6,
    TNOTEQUALS=7,TLESSTHAN=8,TGREATERTHAN=9,TLESSTHANEQUALS=10,TGREATERTHANEQUALS=11,TADD=12,
    TMINUS=13,TDIGIT=14,TSTRING=15,IDENTIFIER=16,LPAREN=17,RPAREN=18,
    TCOMMA=19,TMULT=20,TDIV=21,TSELECT=22,TFROM=23,TWHERE=24,
    TORDER=25,TBY=26,TASC=27,TDESC=28,TTRUE=29,TFALSE=30,
    TUPDATE=31,TSET=32,TDELETE=33,TINSERT=34,TINTO=35,TVALUES=36,
    TCREATE=37};

internal partial struct ValueType
{ 
        public NodeAst n;
        public string s;
}
// Abstract base class for GPLEX scanners
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
internal abstract class ScanBase : AbstractScanner<ValueType,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

// Utility class for encapsulating token information
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
internal class ScanObj {
  public int token;
  public ValueType yylval;
  public LexLocation yylloc;
  public ScanObj( int t, ValueType val, LexLocation loc ) {
    this.token = t; this.yylval = val; this.yylloc = loc;
  }
}

[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
internal partial class sqlParser: ShiftReduceParser<ValueType, LexLocation>
{
#pragma warning disable 649
  private static Dictionary<int, string> aliases;
#pragma warning restore 649
  private static Rule[] rules = new Rule[65];
  private static State[] states = new State[113];
  private static string[] nonTerms = new string[] {
      "list", "$accept", "stat", "select_stmt", "update_stmt", "delete_stmt", 
      "insert_stmt", "create_table_stmt", "select_field_list", "identifier", 
      "condition", "order_list", "insert_field_list", "values_list", "update_list", 
      "update_item", "simple_expr", "select_field_item", "insert_field_item", 
      "values_item", "expr", "order_item", "equals_expr", "not_equals_expr", 
      "less_than_expr", "greater_than_expr", "less_equals_than_expr", "greater_equals_than_expr", 
      "and_expr", "or_expr", "group_paren_expr", "fcall_expr", "number", "string", 
      "bool", };

  static sqlParser() {
    states[0] = new State(new int[]{22,5,31,72,33,85,34,91,37,111},new int[]{-1,1,-3,3,-4,4,-5,71,-6,84,-7,90,-8,110});
    states[1] = new State(new int[]{3,2});
    states[2] = new State(-1);
    states[3] = new State(-2);
    states[4] = new State(-3);
    states[5] = new State(new int[]{16,19,20,69},new int[]{-9,6,-18,70,-10,68});
    states[6] = new State(new int[]{23,7,19,66});
    states[7] = new State(new int[]{16,19},new int[]{-10,8});
    states[8] = new State(new int[]{24,9,25,63,3,-8});
    states[9] = new State(new int[]{16,48,14,52,15,54,29,56,30,57,17,59},new int[]{-11,10,-21,37,-23,38,-24,39,-25,40,-26,41,-27,42,-28,43,-29,44,-30,45,-17,46,-10,47,-33,51,-34,53,-35,55,-31,58,-32,62});
    states[10] = new State(new int[]{25,11,6,21,7,23,8,25,9,27,10,29,11,31,5,33,4,35,3,-9});
    states[11] = new State(new int[]{26,12});
    states[12] = new State(new int[]{16,19},new int[]{-12,13,-22,20,-10,16});
    states[13] = new State(new int[]{19,14,3,-11});
    states[14] = new State(new int[]{16,19},new int[]{-22,15,-10,16});
    states[15] = new State(-29);
    states[16] = new State(new int[]{27,17,28,18,19,-31,3,-31});
    states[17] = new State(-32);
    states[18] = new State(-33);
    states[19] = new State(-60);
    states[20] = new State(-30);
    states[21] = new State(new int[]{16,48,14,52,15,54,29,56,30,57,17,59},new int[]{-11,22,-21,37,-23,38,-24,39,-25,40,-26,41,-27,42,-28,43,-29,44,-30,45,-17,46,-10,47,-33,51,-34,53,-35,55,-31,58,-32,62});
    states[22] = new State(new int[]{6,-48,7,-48,8,25,9,27,10,29,11,31,5,-48,4,-48,25,-48,3,-48,18,-48,19,-48});
    states[23] = new State(new int[]{16,48,14,52,15,54,29,56,30,57,17,59},new int[]{-11,24,-21,37,-23,38,-24,39,-25,40,-26,41,-27,42,-28,43,-29,44,-30,45,-17,46,-10,47,-33,51,-34,53,-35,55,-31,58,-32,62});
    states[24] = new State(new int[]{6,-49,7,-49,8,25,9,27,10,29,11,31,5,-49,4,-49,25,-49,3,-49,18,-49,19,-49});
    states[25] = new State(new int[]{16,48,14,52,15,54,29,56,30,57,17,59},new int[]{-11,26,-21,37,-23,38,-24,39,-25,40,-26,41,-27,42,-28,43,-29,44,-30,45,-17,46,-10,47,-33,51,-34,53,-35,55,-31,58,-32,62});
    states[26] = new State(-50);
    states[27] = new State(new int[]{16,48,14,52,15,54,29,56,30,57,17,59},new int[]{-11,28,-21,37,-23,38,-24,39,-25,40,-26,41,-27,42,-28,43,-29,44,-30,45,-17,46,-10,47,-33,51,-34,53,-35,55,-31,58,-32,62});
    states[28] = new State(-51);
    states[29] = new State(new int[]{16,48,14,52,15,54,29,56,30,57,17,59},new int[]{-11,30,-21,37,-23,38,-24,39,-25,40,-26,41,-27,42,-28,43,-29,44,-30,45,-17,46,-10,47,-33,51,-34,53,-35,55,-31,58,-32,62});
    states[30] = new State(-53);
    states[31] = new State(new int[]{16,48,14,52,15,54,29,56,30,57,17,59},new int[]{-11,32,-21,37,-23,38,-24,39,-25,40,-26,41,-27,42,-28,43,-29,44,-30,45,-17,46,-10,47,-33,51,-34,53,-35,55,-31,58,-32,62});
    states[32] = new State(-52);
    states[33] = new State(new int[]{16,48,14,52,15,54,29,56,30,57,17,59},new int[]{-11,34,-21,37,-23,38,-24,39,-25,40,-26,41,-27,42,-28,43,-29,44,-30,45,-17,46,-10,47,-33,51,-34,53,-35,55,-31,58,-32,62});
    states[34] = new State(new int[]{6,21,7,23,8,25,9,27,10,29,11,31,5,-46,4,-46,25,-46,3,-46,18,-46,19,-46});
    states[35] = new State(new int[]{16,48,14,52,15,54,29,56,30,57,17,59},new int[]{-11,36,-21,37,-23,38,-24,39,-25,40,-26,41,-27,42,-28,43,-29,44,-30,45,-17,46,-10,47,-33,51,-34,53,-35,55,-31,58,-32,62});
    states[36] = new State(new int[]{6,21,7,23,8,25,9,27,10,29,11,31,5,33,4,-47,25,-47,3,-47,18,-47,19,-47});
    states[37] = new State(-34);
    states[38] = new State(-35);
    states[39] = new State(-36);
    states[40] = new State(-37);
    states[41] = new State(-38);
    states[42] = new State(-39);
    states[43] = new State(-40);
    states[44] = new State(-41);
    states[45] = new State(-42);
    states[46] = new State(-43);
    states[47] = new State(-56);
    states[48] = new State(new int[]{17,49,25,-60,6,-60,7,-60,8,-60,9,-60,10,-60,11,-60,5,-60,4,-60,3,-60,18,-60,19,-60});
    states[49] = new State(new int[]{18,50});
    states[50] = new State(-54);
    states[51] = new State(-57);
    states[52] = new State(-61);
    states[53] = new State(-58);
    states[54] = new State(-62);
    states[55] = new State(-59);
    states[56] = new State(-63);
    states[57] = new State(-64);
    states[58] = new State(-44);
    states[59] = new State(new int[]{16,48,14,52,15,54,29,56,30,57,17,59},new int[]{-11,60,-21,37,-23,38,-24,39,-25,40,-26,41,-27,42,-28,43,-29,44,-30,45,-17,46,-10,47,-33,51,-34,53,-35,55,-31,58,-32,62});
    states[60] = new State(new int[]{18,61,6,21,7,23,8,25,9,27,10,29,11,31,5,33,4,35});
    states[61] = new State(-55);
    states[62] = new State(-45);
    states[63] = new State(new int[]{26,64});
    states[64] = new State(new int[]{16,19},new int[]{-12,65,-22,20,-10,16});
    states[65] = new State(new int[]{19,14,3,-10});
    states[66] = new State(new int[]{16,19,20,69},new int[]{-18,67,-10,68});
    states[67] = new State(-19);
    states[68] = new State(-21);
    states[69] = new State(-22);
    states[70] = new State(-20);
    states[71] = new State(-4);
    states[72] = new State(new int[]{16,19},new int[]{-10,73});
    states[73] = new State(new int[]{32,74});
    states[74] = new State(new int[]{16,19},new int[]{-15,75,-16,83,-10,80});
    states[75] = new State(new int[]{24,76,19,78});
    states[76] = new State(new int[]{16,48,14,52,15,54,29,56,30,57,17,59},new int[]{-11,77,-21,37,-23,38,-24,39,-25,40,-26,41,-27,42,-28,43,-29,44,-30,45,-17,46,-10,47,-33,51,-34,53,-35,55,-31,58,-32,62});
    states[77] = new State(new int[]{6,21,7,23,8,25,9,27,10,29,11,31,5,33,4,35,3,-13});
    states[78] = new State(new int[]{16,19},new int[]{-16,79,-10,80});
    states[79] = new State(-16);
    states[80] = new State(new int[]{6,81});
    states[81] = new State(new int[]{16,19,14,52,15,54,29,56,30,57},new int[]{-17,82,-10,47,-33,51,-34,53,-35,55});
    states[82] = new State(-18);
    states[83] = new State(-17);
    states[84] = new State(-5);
    states[85] = new State(new int[]{23,86});
    states[86] = new State(new int[]{16,19},new int[]{-10,87});
    states[87] = new State(new int[]{24,88});
    states[88] = new State(new int[]{16,48,14,52,15,54,29,56,30,57,17,59},new int[]{-11,89,-21,37,-23,38,-24,39,-25,40,-26,41,-27,42,-28,43,-29,44,-30,45,-17,46,-10,47,-33,51,-34,53,-35,55,-31,58,-32,62});
    states[89] = new State(new int[]{6,21,7,23,8,25,9,27,10,29,11,31,5,33,4,35,3,-14});
    states[90] = new State(-6);
    states[91] = new State(new int[]{35,92});
    states[92] = new State(new int[]{16,19},new int[]{-10,93});
    states[93] = new State(new int[]{17,94});
    states[94] = new State(new int[]{16,19},new int[]{-13,95,-19,109,-10,108});
    states[95] = new State(new int[]{18,96,19,106});
    states[96] = new State(new int[]{36,97});
    states[97] = new State(new int[]{17,98});
    states[98] = new State(new int[]{16,48,14,52,15,54,29,56,30,57,17,59},new int[]{-14,99,-20,105,-21,103,-23,38,-11,104,-24,39,-25,40,-26,41,-27,42,-28,43,-29,44,-30,45,-17,46,-10,47,-33,51,-34,53,-35,55,-31,58,-32,62});
    states[99] = new State(new int[]{18,100,19,101});
    states[100] = new State(-12);
    states[101] = new State(new int[]{16,48,14,52,15,54,29,56,30,57,17,59},new int[]{-20,102,-21,103,-23,38,-11,104,-24,39,-25,40,-26,41,-27,42,-28,43,-29,44,-30,45,-17,46,-10,47,-33,51,-34,53,-35,55,-31,58,-32,62});
    states[102] = new State(-26);
    states[103] = new State(new int[]{18,-28,19,-28,6,-34,7,-34,8,-34,9,-34,10,-34,11,-34,5,-34,4,-34});
    states[104] = new State(new int[]{6,21,7,23,8,25,9,27,10,29,11,31,5,33,4,35});
    states[105] = new State(-27);
    states[106] = new State(new int[]{16,19},new int[]{-19,107,-10,108});
    states[107] = new State(-23);
    states[108] = new State(-25);
    states[109] = new State(-24);
    states[110] = new State(-7);
    states[111] = new State(new int[]{16,19},new int[]{-10,112});
    states[112] = new State(-15);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-2, new int[]{-1,3});
    rules[2] = new Rule(-1, new int[]{-3});
    rules[3] = new Rule(-3, new int[]{-4});
    rules[4] = new Rule(-3, new int[]{-5});
    rules[5] = new Rule(-3, new int[]{-6});
    rules[6] = new Rule(-3, new int[]{-7});
    rules[7] = new Rule(-3, new int[]{-8});
    rules[8] = new Rule(-4, new int[]{22,-9,23,-10});
    rules[9] = new Rule(-4, new int[]{22,-9,23,-10,24,-11});
    rules[10] = new Rule(-4, new int[]{22,-9,23,-10,25,26,-12});
    rules[11] = new Rule(-4, new int[]{22,-9,23,-10,24,-11,25,26,-12});
    rules[12] = new Rule(-7, new int[]{34,35,-10,17,-13,18,36,17,-14,18});
    rules[13] = new Rule(-5, new int[]{31,-10,32,-15,24,-11});
    rules[14] = new Rule(-6, new int[]{33,23,-10,24,-11});
    rules[15] = new Rule(-8, new int[]{37,-10});
    rules[16] = new Rule(-15, new int[]{-15,19,-16});
    rules[17] = new Rule(-15, new int[]{-16});
    rules[18] = new Rule(-16, new int[]{-10,6,-17});
    rules[19] = new Rule(-9, new int[]{-9,19,-18});
    rules[20] = new Rule(-9, new int[]{-18});
    rules[21] = new Rule(-18, new int[]{-10});
    rules[22] = new Rule(-18, new int[]{20});
    rules[23] = new Rule(-13, new int[]{-13,19,-19});
    rules[24] = new Rule(-13, new int[]{-19});
    rules[25] = new Rule(-19, new int[]{-10});
    rules[26] = new Rule(-14, new int[]{-14,19,-20});
    rules[27] = new Rule(-14, new int[]{-20});
    rules[28] = new Rule(-20, new int[]{-21});
    rules[29] = new Rule(-12, new int[]{-12,19,-22});
    rules[30] = new Rule(-12, new int[]{-22});
    rules[31] = new Rule(-22, new int[]{-10});
    rules[32] = new Rule(-22, new int[]{-10,27});
    rules[33] = new Rule(-22, new int[]{-10,28});
    rules[34] = new Rule(-11, new int[]{-21});
    rules[35] = new Rule(-21, new int[]{-23});
    rules[36] = new Rule(-21, new int[]{-24});
    rules[37] = new Rule(-21, new int[]{-25});
    rules[38] = new Rule(-21, new int[]{-26});
    rules[39] = new Rule(-21, new int[]{-27});
    rules[40] = new Rule(-21, new int[]{-28});
    rules[41] = new Rule(-21, new int[]{-29});
    rules[42] = new Rule(-21, new int[]{-30});
    rules[43] = new Rule(-21, new int[]{-17});
    rules[44] = new Rule(-21, new int[]{-31});
    rules[45] = new Rule(-21, new int[]{-32});
    rules[46] = new Rule(-29, new int[]{-11,5,-11});
    rules[47] = new Rule(-30, new int[]{-11,4,-11});
    rules[48] = new Rule(-23, new int[]{-11,6,-11});
    rules[49] = new Rule(-24, new int[]{-11,7,-11});
    rules[50] = new Rule(-25, new int[]{-11,8,-11});
    rules[51] = new Rule(-26, new int[]{-11,9,-11});
    rules[52] = new Rule(-28, new int[]{-11,11,-11});
    rules[53] = new Rule(-27, new int[]{-11,10,-11});
    rules[54] = new Rule(-32, new int[]{16,17,18});
    rules[55] = new Rule(-31, new int[]{17,-11,18});
    rules[56] = new Rule(-17, new int[]{-10});
    rules[57] = new Rule(-17, new int[]{-33});
    rules[58] = new Rule(-17, new int[]{-34});
    rules[59] = new Rule(-17, new int[]{-35});
    rules[60] = new Rule(-10, new int[]{16});
    rules[61] = new Rule(-33, new int[]{14});
    rules[62] = new Rule(-34, new int[]{15});
    rules[63] = new Rule(-35, new int[]{29});
    rules[64] = new Rule(-35, new int[]{30});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Token.error, (int)Token.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
#pragma warning disable 162, 1522
    switch (action)
    {
      case 2: // list -> stat
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-1].n; }
        break;
      case 3: // stat -> select_stmt
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-1].n; }
        break;
      case 4: // stat -> update_stmt
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-1].n; }
        break;
      case 5: // stat -> delete_stmt
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-1].n; }
        break;
      case 6: // stat -> insert_stmt
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-1].n; }
        break;
      case 7: // stat -> create_table_stmt
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-1].n; }
        break;
      case 8: // select_stmt -> TSELECT, select_field_list, TFROM, identifier
{ CurrentSemanticValue.n = new(NodeType.Select, ValueStack[ValueStack.Depth-3].n, ValueStack[ValueStack.Depth-1].n, null, null, null); }
        break;
      case 9: // select_stmt -> TSELECT, select_field_list, TFROM, identifier, TWHERE, condition
{ CurrentSemanticValue.n = new(NodeType.Select, ValueStack[ValueStack.Depth-5].n, ValueStack[ValueStack.Depth-3].n, ValueStack[ValueStack.Depth-1].n, null, null); }
        break;
      case 10: // select_stmt -> TSELECT, select_field_list, TFROM, identifier, TORDER, TBY, 
               //                order_list
{ CurrentSemanticValue.n = new(NodeType.Select, ValueStack[ValueStack.Depth-6].n, ValueStack[ValueStack.Depth-4].n, null, ValueStack[ValueStack.Depth-1].n, null); }
        break;
      case 11: // select_stmt -> TSELECT, select_field_list, TFROM, identifier, TWHERE, condition, 
               //                TORDER, TBY, order_list
{ CurrentSemanticValue.n = new(NodeType.Select, ValueStack[ValueStack.Depth-8].n, ValueStack[ValueStack.Depth-6].n, ValueStack[ValueStack.Depth-4].n, ValueStack[ValueStack.Depth-1].n, null); }
        break;
      case 12: // insert_stmt -> TINSERT, TINTO, identifier, LPAREN, insert_field_list, RPAREN, 
               //                TVALUES, LPAREN, values_list, RPAREN
{ CurrentSemanticValue.n = new(NodeType.Insert, ValueStack[ValueStack.Depth-8].n, ValueStack[ValueStack.Depth-6].n, ValueStack[ValueStack.Depth-2].n, null, null); }
        break;
      case 13: // update_stmt -> TUPDATE, identifier, TSET, update_list, TWHERE, condition
{ CurrentSemanticValue.n = new(NodeType.Update, ValueStack[ValueStack.Depth-5].n, ValueStack[ValueStack.Depth-3].n, ValueStack[ValueStack.Depth-1].n, null, null); }
        break;
      case 14: // delete_stmt -> TDELETE, TFROM, identifier, TWHERE, condition
{ CurrentSemanticValue.n = new(NodeType.Delete, ValueStack[ValueStack.Depth-3].n, ValueStack[ValueStack.Depth-1].n, null, null, null); }
        break;
      case 15: // create_table_stmt -> TCREATE, identifier
{ CurrentSemanticValue.n = new(NodeType.CreateTable, ValueStack[ValueStack.Depth-1].n, null, null, null, null); }
        break;
      case 16: // update_list -> update_list, TCOMMA, update_item
{ CurrentSemanticValue.n = new(NodeType.UpdateList, ValueStack[ValueStack.Depth-3].n, ValueStack[ValueStack.Depth-1].n, null, null, null); }
        break;
      case 17: // update_list -> update_item
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-1].n; CurrentSemanticValue.s = ValueStack[ValueStack.Depth-1].s; }
        break;
      case 18: // update_item -> identifier, TEQUALS, simple_expr
{ CurrentSemanticValue.n = new(NodeType.UpdateItem, ValueStack[ValueStack.Depth-3].n, ValueStack[ValueStack.Depth-1].n, null, null, null); }
        break;
      case 19: // select_field_list -> select_field_list, TCOMMA, select_field_item
{ CurrentSemanticValue.n = new(NodeType.IdentifierList, ValueStack[ValueStack.Depth-3].n, ValueStack[ValueStack.Depth-1].n, null, null, null); }
        break;
      case 20: // select_field_list -> select_field_item
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-1].n; CurrentSemanticValue.s = ValueStack[ValueStack.Depth-1].s; }
        break;
      case 21: // select_field_item -> identifier
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-1].n; CurrentSemanticValue.s = ValueStack[ValueStack.Depth-1].s; }
        break;
      case 22: // select_field_item -> TMULT
{ CurrentSemanticValue.n = new(NodeType.ExprAllFields, null, null, null, null, null); }
        break;
      case 23: // insert_field_list -> insert_field_list, TCOMMA, insert_field_item
{ CurrentSemanticValue.n = new(NodeType.IdentifierList, ValueStack[ValueStack.Depth-3].n, ValueStack[ValueStack.Depth-1].n, null, null, null); }
        break;
      case 24: // insert_field_list -> insert_field_item
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-1].n; CurrentSemanticValue.s = ValueStack[ValueStack.Depth-1].s; }
        break;
      case 25: // insert_field_item -> identifier
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-1].n; CurrentSemanticValue.s = ValueStack[ValueStack.Depth-1].s; }
        break;
      case 26: // values_list -> values_list, TCOMMA, values_item
{ CurrentSemanticValue.n = new(NodeType.ExprList, ValueStack[ValueStack.Depth-3].n, ValueStack[ValueStack.Depth-1].n, null, null, null); }
        break;
      case 27: // values_list -> values_item
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-1].n; CurrentSemanticValue.s = ValueStack[ValueStack.Depth-1].s; }
        break;
      case 28: // values_item -> expr
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-1].n; CurrentSemanticValue.s = ValueStack[ValueStack.Depth-1].s; }
        break;
      case 29: // order_list -> order_list, TCOMMA, order_item
{ CurrentSemanticValue.n = new(NodeType.IdentifierList, ValueStack[ValueStack.Depth-3].n, ValueStack[ValueStack.Depth-1].n, null, null, null); }
        break;
      case 30: // order_list -> order_item
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-1].n; CurrentSemanticValue.s = ValueStack[ValueStack.Depth-1].s; }
        break;
      case 31: // order_item -> identifier
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-1].n; CurrentSemanticValue.s = ValueStack[ValueStack.Depth-1].s; }
        break;
      case 32: // order_item -> identifier, TASC
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-2].n; CurrentSemanticValue.s = ValueStack[ValueStack.Depth-2].s; }
        break;
      case 33: // order_item -> identifier, TDESC
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-2].n; CurrentSemanticValue.s = ValueStack[ValueStack.Depth-2].s; }
        break;
      case 34: // condition -> expr
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-1].n; CurrentSemanticValue.s = ValueStack[ValueStack.Depth-1].s; }
        break;
      case 35: // expr -> equals_expr
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-1].n; }
        break;
      case 36: // expr -> not_equals_expr
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-1].n; }
        break;
      case 37: // expr -> less_than_expr
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-1].n; }
        break;
      case 38: // expr -> greater_than_expr
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-1].n; }
        break;
      case 39: // expr -> less_equals_than_expr
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-1].n; }
        break;
      case 40: // expr -> greater_equals_than_expr
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-1].n; }
        break;
      case 41: // expr -> and_expr
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-1].n; }
        break;
      case 42: // expr -> or_expr
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-1].n; }
        break;
      case 43: // expr -> simple_expr
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-1].n; }
        break;
      case 44: // expr -> group_paren_expr
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-1].n; }
        break;
      case 45: // expr -> fcall_expr
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-1].n; }
        break;
      case 46: // and_expr -> condition, TAND, condition
{ CurrentSemanticValue.n = new(NodeType.ExprAnd, ValueStack[ValueStack.Depth-3].n, ValueStack[ValueStack.Depth-1].n, null, null, null); }
        break;
      case 47: // or_expr -> condition, TOR, condition
{ CurrentSemanticValue.n = new(NodeType.ExprOr, ValueStack[ValueStack.Depth-3].n, ValueStack[ValueStack.Depth-1].n, null, null, null); }
        break;
      case 48: // equals_expr -> condition, TEQUALS, condition
{ CurrentSemanticValue.n = new(NodeType.ExprEquals, ValueStack[ValueStack.Depth-3].n, ValueStack[ValueStack.Depth-1].n, null, null, null); }
        break;
      case 49: // not_equals_expr -> condition, TNOTEQUALS, condition
{ CurrentSemanticValue.n = new(NodeType.ExprNotEquals, ValueStack[ValueStack.Depth-3].n, ValueStack[ValueStack.Depth-1].n, null, null, null); }
        break;
      case 50: // less_than_expr -> condition, TLESSTHAN, condition
{ CurrentSemanticValue.n = new(NodeType.ExprLessThan, ValueStack[ValueStack.Depth-3].n, ValueStack[ValueStack.Depth-1].n, null, null, null); }
        break;
      case 51: // greater_than_expr -> condition, TGREATERTHAN, condition
{ CurrentSemanticValue.n = new(NodeType.ExprGreaterThan, ValueStack[ValueStack.Depth-3].n, ValueStack[ValueStack.Depth-1].n, null, null, null); }
        break;
      case 52: // greater_equals_than_expr -> condition, TGREATERTHANEQUALS, condition
{ CurrentSemanticValue.n = new(NodeType.ExprGreaterEqualsThan, ValueStack[ValueStack.Depth-3].n, ValueStack[ValueStack.Depth-1].n, null, null, null); }
        break;
      case 53: // less_equals_than_expr -> condition, TLESSTHANEQUALS, condition
{ CurrentSemanticValue.n = new(NodeType.ExprLessEqualsThan, ValueStack[ValueStack.Depth-3].n, ValueStack[ValueStack.Depth-1].n, null, null, null); }
        break;
      case 54: // fcall_expr -> IDENTIFIER, LPAREN, RPAREN
{ CurrentSemanticValue.n = new(NodeType.ExprFuncCall, ValueStack[ValueStack.Depth-3].n, null, null, null, null); }
        break;
      case 55: // group_paren_expr -> LPAREN, condition, RPAREN
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-2].n; CurrentSemanticValue.s = ValueStack[ValueStack.Depth-2].s; }
        break;
      case 56: // simple_expr -> identifier
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-1].n; CurrentSemanticValue.s = ValueStack[ValueStack.Depth-1].s; }
        break;
      case 57: // simple_expr -> number
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-1].n; CurrentSemanticValue.s = ValueStack[ValueStack.Depth-1].s; }
        break;
      case 58: // simple_expr -> string
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-1].n; CurrentSemanticValue.s = ValueStack[ValueStack.Depth-1].s; }
        break;
      case 59: // simple_expr -> bool
{ CurrentSemanticValue.n = ValueStack[ValueStack.Depth-1].n; CurrentSemanticValue.s = ValueStack[ValueStack.Depth-1].s; }
        break;
      case 60: // identifier -> IDENTIFIER
{ CurrentSemanticValue.n = new(NodeType.Identifier, null, null, null, null, CurrentSemanticValue.s); }
        break;
      case 61: // number -> TDIGIT
{ CurrentSemanticValue.n = new(NodeType.Number, null, null, null, null, CurrentSemanticValue.s); }
        break;
      case 62: // string -> TSTRING
{ CurrentSemanticValue.n = new(NodeType.String, null, null, null, null, CurrentSemanticValue.s); }
        break;
      case 63: // bool -> TTRUE
{ CurrentSemanticValue.n = new(NodeType.Bool, null, null, null, null, "true"); }
        break;
      case 64: // bool -> TFALSE
{ CurrentSemanticValue.n = new(NodeType.Bool, null, null, null, null, "false"); }
        break;
    }
#pragma warning restore 162, 1522
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliases != null && aliases.ContainsKey(terminal))
        return aliases[terminal];
    else if (((Token)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Token)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

}
}
