/**
 * This file is part of CamusDB
 *
 * For the full copyright and license information, please view the LICENSE.txt
 * file that was distributed with this source code.
 */

using CamusDB.Core.Catalogs.Models;
using CamusDB.Core.CommandsExecutor.Models;

namespace CamusDB.Core.CommandsExecutor.Controllers.Functions;

/// <summary>
/// Hands a column default its next value out of the run the statement reserved.
///
/// <para>Separate from <see cref="SequenceScalarFunctions"/> because a default has no call site:
/// the column is simply absent from the statement, so there is no <c>nextval</c> node to evaluate
/// and no function name to dispatch on. What the two share is the cursor — the same reserved run
/// in the same parameter dictionary — so a column default and an explicit <c>nextval</c> on the
/// same sequence in one statement draw from one reservation rather than two.</para>
/// </summary>
internal static class SequenceDefaults
{
    /// <summary>
    /// Takes the next value of <paramref name="sequenceId"/>'s reserved run.
    /// </summary>
    /// <remarks>
    /// A missing or exhausted run is an engine defect rather than a user error: the insert path
    /// counts the rows and reserves exactly that many values before it shapes the first one. It is
    /// raised loudly instead of returning NULL, because a NULL written into an identity column is
    /// a silent data fault that surfaces much later, if at all.
    /// </remarks>
    internal static ColumnValue TakeNextValue(
        string sequenceId, string columnName, Dictionary<string, ColumnValue>? parameters)
    {
        if (parameters is null)
            throw Unreserved(columnName);

        // The one cursor, drawn the one way: a column default and an explicit nextval on the same
        // sequence share a single reservation, so they must share the code that consumes it.
        return SequenceScalarFunctions.TakeFromRun(
            sequenceId, columnName, parameters, () => Unreserved(columnName));
    }

    /// <summary>
    /// Refuses an INSERT that supplies a value for a <c>GENERATED ALWAYS AS IDENTITY</c> column.
    /// That refusal is the only thing separating <c>ALWAYS</c> from <c>BY DEFAULT</c>, so it has to
    /// be explicit rather than a silent override of what the caller wrote.
    /// </summary>
    internal static void RequireNoValueForAlwaysIdentity(TableSchema schema, IReadOnlyList<string> targetColumns)
    {
        if (schema.Columns is null)
            return;

        foreach (TableColumnSchema column in schema.Columns)
        {
            if (!column.IdentityAlways)
                continue;

            foreach (string target in targetColumns)
            {
                if (!string.Equals(target, column.Name, StringComparison.OrdinalIgnoreCase))
                    continue;

                throw new CamusDBException(
                    CamusDBErrorCodes.InvalidInput,
                    $"Column '{column.Name}' is GENERATED ALWAYS AS IDENTITY, so a value cannot be supplied " +
                    "for it. Omit the column, or declare it GENERATED BY DEFAULT AS IDENTITY.");
            }
        }
    }

    private static CamusDBException Unreserved(string columnName)
        => new(
            CamusDBErrorCodes.SequenceCallNotAllowedHere,
            $"The default of column '{columnName}' draws from a sequence, and this path did not reserve any " +
            "values before shaping the row. A sequence default is only applied on INSERT and on an " +
            "ALTER TABLE backfill.");
}
