
/**
 * This file is part of CamusDB
 *
 * For the full copyright and license information, please view the LICENSE.txt
 * file that was distributed with this source code.
 */

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

using Kommander.Data;
using Kommander.Time;
using Kommander.WAL;

using Kahuna;
using Kahuna.Server.KeyValues;
using Kahuna.Server.KeyValues.Transactions.Data;
using Kahuna.Server.Locks;
using Kahuna.Server.Locks.Data;
using Kahuna.Shared.Communication.Rest;
using Kahuna.Shared.KeyValue;
using Kahuna.Shared.Locks;
using Kahuna.Shared.Sequences;

namespace CamusDB.Tests.Storage;

/// <summary>
/// Test-only base that forwards every <see cref="IKahuna"/> member to a wrapped inner instance.
/// Fault-injecting fakes derive from this and <c>override</c> only the handful of operations they
/// intercept, so they stay compilable as the Kahuna interface evolves instead of hand-implementing
/// all ~100 members. Every member is <c>virtual</c>; <see cref="inner"/> is protected so overrides
/// can fall through to the real node.
/// </summary>
internal abstract class DelegatingKahuna : IKahuna
{
    protected readonly IKahuna inner;

    protected DelegatingKahuna(IKahuna inner) => this.inner = inner;

        public virtual Task<(LockResponseType, long)> LocateAndTryLock(string resource, byte[] owner, int expiresMs, LockDurability durability, CancellationToken cancellationToken) => inner.LocateAndTryLock(resource, owner, expiresMs, durability, cancellationToken);
        public virtual Task<(LockResponseType, long)> LocateAndTryExtendLock(string resource, byte[] owner, int expiresMs, LockDurability durability, CancellationToken cancellationToken) => inner.LocateAndTryExtendLock(resource, owner, expiresMs, durability, cancellationToken);
        public virtual Task<LockResponseType> LocateAndTryUnlock(string resource, byte[] owner, LockDurability durability, CancellationToken cancellationToken) => inner.LocateAndTryUnlock(resource, owner, durability, cancellationToken);
        public virtual Task<(LockResponseType, ReadOnlyLockEntry?)> LocateAndGetLock(string resource, LockDurability durability, CancellationToken cancellationToken) => inner.LocateAndGetLock(resource, durability, cancellationToken);
        public virtual Task<(LockResponseType, long)> TryLock(string resource, byte[] owner, int expiresMs, LockDurability durability) => inner.TryLock(resource, owner, expiresMs, durability);
        public virtual Task<(LockResponseType, long)> TryExtendLock(string resource, byte[] owner, int expiresMs, LockDurability durability) => inner.TryExtendLock(resource, owner, expiresMs, durability);
        public virtual Task<LockResponseType> TryUnlock(string resource, byte[] owner, LockDurability durability) => inner.TryUnlock(resource, owner, durability);
        public virtual Task<(LockResponseType, ReadOnlyLockEntry?)> GetLock(string resource, LockDurability durability) => inner.GetLock(resource, durability);
        public virtual Task<(KeyValueResponseType, long, HLCTimestamp)> LocateAndTrySetKeyValue(HLCTimestamp transactionId, string key, byte[]? value, byte[]? compareValue, long compareRevision, KeyValueFlags flags, int expiresMs, KeyValueDurability durability, CancellationToken cancellationToken, long routedGeneration = 0, string coordinatorKey = "", TransactionOperationId operationId = default) => inner.LocateAndTrySetKeyValue(transactionId, key, value, compareValue, compareRevision, flags, expiresMs, durability, cancellationToken, routedGeneration, coordinatorKey, operationId);
        public virtual Task<List<KahunaSetKeyValueResponseItem>> LocateAndTrySetManyKeyValue(List<KahunaSetKeyValueRequestItem> setManyItems, CancellationToken cancellationToken, string coordinatorKey = "", TransactionOperationId operationId = default) => inner.LocateAndTrySetManyKeyValue(setManyItems, cancellationToken, coordinatorKey, operationId);
        public virtual Task<List<KahunaDeleteKeyValueResponseItem>> LocateAndTryDeleteManyKeyValue(List<KahunaDeleteKeyValueRequestItem> deleteManyItems, CancellationToken cancellationToken, string coordinatorKey = "", TransactionOperationId operationId = default) => inner.LocateAndTryDeleteManyKeyValue(deleteManyItems, cancellationToken, coordinatorKey, operationId);
        public virtual Task<(KeyValueResponseType, ReadOnlyKeyValueEntry?)> LocateAndTryExistsValue(HLCTimestamp transactionId, string key, long revision, HLCTimestamp readTimestamp, KeyValueDurability durability, CancellationToken cancellationToken, string coordinatorKey = "", TransactionOperationId operationId = default) => inner.LocateAndTryExistsValue(transactionId, key, revision, readTimestamp, durability, cancellationToken, coordinatorKey, operationId);
        public virtual Task<KeyValueResponseType> LocateAndTryCheckWriteIntent(HLCTimestamp transactionId, string key, KeyValueDurability durability, CancellationToken cancellationToken) => inner.LocateAndTryCheckWriteIntent(transactionId, key, durability, cancellationToken);
        public virtual Task<List<(KeyValueResponseType type, string key, KeyValueDurability durability)>> LocateAndTryCheckManyWriteIntents(HLCTimestamp transactionId, List<(string key, KeyValueDurability durability)> keys, CancellationToken cancellationToken) => inner.LocateAndTryCheckManyWriteIntents(transactionId, keys, cancellationToken);
        public virtual Task<(KeyValueResponseType, ReadOnlyKeyValueEntry?)> LocateAndTryGetValue(HLCTimestamp transactionId, string key, long revision, HLCTimestamp readTimestamp, KeyValueDurability durability, CancellationToken cancellationToken, string coordinatorKey = "", TransactionOperationId operationId = default) => inner.LocateAndTryGetValue(transactionId, key, revision, readTimestamp, durability, cancellationToken, coordinatorKey, operationId);
        public virtual Task<List<(KeyValueResponseType, string, KeyValueDurability, ReadOnlyKeyValueEntry?)>> LocateAndTryGetManyValues(HLCTimestamp transactionId, HLCTimestamp readTimestamp, List<(string key, long revision, KeyValueDurability durability)> keys, CancellationToken cancellationToken, string coordinatorKey = "", TransactionOperationId operationId = default) => inner.LocateAndTryGetManyValues(transactionId, readTimestamp, keys, cancellationToken, coordinatorKey, operationId);
        public virtual Task<List<(KeyValueResponseType, string, KeyValueDurability, ReadOnlyKeyValueEntry?)>> LocateAndTryExistsManyValues(HLCTimestamp transactionId, HLCTimestamp readTimestamp, List<(string key, long revision, KeyValueDurability durability)> keys, CancellationToken cancellationToken, string coordinatorKey = "", TransactionOperationId operationId = default) => inner.LocateAndTryExistsManyValues(transactionId, readTimestamp, keys, cancellationToken, coordinatorKey, operationId);
        public virtual Task<(KeyValueResponseType, long, HLCTimestamp)> LocateAndTryDeleteKeyValue(HLCTimestamp transactionId, string key, KeyValueDurability durability, CancellationToken cancellationToken, string coordinatorKey = "", TransactionOperationId operationId = default) => inner.LocateAndTryDeleteKeyValue(transactionId, key, durability, cancellationToken, coordinatorKey, operationId);
        public virtual Task<(KeyValueResponseType, long, HLCTimestamp)> LocateAndTryExtendKeyValue(HLCTimestamp transactionId, string key, int expiresMs, KeyValueDurability durability, CancellationToken cancellationToken, string coordinatorKey = "", TransactionOperationId operationId = default) => inner.LocateAndTryExtendKeyValue(transactionId, key, expiresMs, durability, cancellationToken, coordinatorKey, operationId);
        public virtual Task<KeyValueGetByBucketResult> LocateAndGetByBucket(HLCTimestamp transactionId, string prefixedKey, HLCTimestamp readTimestamp, KeyValueDurability durability, CancellationToken cancellationToken, string coordinatorKey = "", TransactionOperationId operationId = default) => inner.LocateAndGetByBucket(transactionId, prefixedKey, readTimestamp, durability, cancellationToken, coordinatorKey, operationId);
        public virtual Task<KeyValueGetByRangeResult> LocateAndGetByRange(HLCTimestamp transactionId, string prefix, string? startKey, bool startInclusive, string? endKey, bool endInclusive, int limit, HLCTimestamp readTimestamp, KeyValueDurability durability, CancellationToken cancellationToken, string coordinatorKey = "", TransactionOperationId operationId = default) => inner.LocateAndGetByRange(transactionId, prefix, startKey, startInclusive, endKey, endInclusive, limit, readTimestamp, durability, cancellationToken, coordinatorKey, operationId);
        public virtual IAsyncEnumerable<(string Key, ReadOnlyKeyValueEntry Entry)> LocateAndScanRange(HLCTimestamp txId, string prefix, string? startKey, bool startInclusive, string? endKey, bool endInclusive, int pageSize, HLCTimestamp readTimestamp, KeyValueDurability durability, CancellationToken ct, string coordinatorKey = "", TransactionOperationId operationId = default) => inner.LocateAndScanRange(txId, prefix, startKey, startInclusive, endKey, endInclusive, pageSize, readTimestamp, durability, ct, coordinatorKey, operationId);
        public virtual Task<(KeyValueResponseType, long, HLCTimestamp)> TrySetKeyValue(HLCTimestamp transactionId, string key, byte[]? value, byte[]? compareValue, long compareRevision, KeyValueFlags flags, int expiresMs, KeyValueDurability durability, long routedGeneration = 0) => inner.TrySetKeyValue(transactionId, key, value, compareValue, compareRevision, flags, expiresMs, durability, routedGeneration);
        public virtual Task<(KeyValueResponseType, long, HLCTimestamp)> TryExtendKeyValue(HLCTimestamp transactionId, string key, int expiresMs, KeyValueDurability durability) => inner.TryExtendKeyValue(transactionId, key, expiresMs, durability);
        public virtual Task<(KeyValueResponseType, long, HLCTimestamp)> TryDeleteKeyValue(HLCTimestamp transactionId, string key, KeyValueDurability durability) => inner.TryDeleteKeyValue(transactionId, key, durability);
        public virtual Task<List<KahunaDeleteKeyValueResponseItem>> DeleteManyNodeKeyValue(List<KahunaDeleteKeyValueRequestItem> items) => inner.DeleteManyNodeKeyValue(items);
        public virtual Task<(KeyValueResponseType, ReadOnlyKeyValueEntry?)> TryGetValue(HLCTimestamp transactionId, string key, long revision, HLCTimestamp readTimestamp, KeyValueDurability durability) => inner.TryGetValue(transactionId, key, revision, readTimestamp, durability);
        public virtual Task<List<(KeyValueResponseType, string, KeyValueDurability, ReadOnlyKeyValueEntry?)>> TryGetManyValues(HLCTimestamp transactionId, HLCTimestamp readTimestamp, List<(string key, long revision, KeyValueDurability durability)> keys) => inner.TryGetManyValues(transactionId, readTimestamp, keys);
        public virtual Task<(KeyValueResponseType, ReadOnlyKeyValueEntry?)> TryExistsValue(HLCTimestamp transactionId, string key, long revision, HLCTimestamp readTimestamp, KeyValueDurability durability) => inner.TryExistsValue(transactionId, key, revision, readTimestamp, durability);
        public virtual Task<List<(KeyValueResponseType, string, KeyValueDurability, ReadOnlyKeyValueEntry?)>> TryExistsManyValues(HLCTimestamp transactionId, HLCTimestamp readTimestamp, List<(string key, long revision, KeyValueDurability durability)> keys) => inner.TryExistsManyValues(transactionId, readTimestamp, keys);
        public virtual Task<KeyValueResponseType> TryCheckWriteIntentValue(HLCTimestamp transactionId, string key, KeyValueDurability durability) => inner.TryCheckWriteIntentValue(transactionId, key, durability);
        public virtual Task<List<(KeyValueResponseType type, string key, KeyValueDurability durability)>> TryCheckManyWriteIntentValues(HLCTimestamp transactionId, List<(string key, KeyValueDurability durability)> keys) => inner.TryCheckManyWriteIntentValues(transactionId, keys);
        public virtual Task<(KeyValueResponseType, string, KeyValueDurability, HLCTimestamp HolderTransactionId)> LocateAndTryAcquireExclusiveLock(HLCTimestamp transactionId, string key, int expiresMs, KeyValueDurability durability, CancellationToken cancellationToken, string coordinatorKey = "", TransactionOperationId operationId = default) => inner.LocateAndTryAcquireExclusiveLock(transactionId, key, expiresMs, durability, cancellationToken, coordinatorKey, operationId);
        public virtual Task<KeyValueResponseType> LocateAndTryAcquireExclusivePrefixLock(HLCTimestamp transactionId, string prefixKey, int expiresMs, KeyValueDurability durability, CancellationToken cancellationToken, string coordinatorKey = "", TransactionOperationId operationId = default) => inner.LocateAndTryAcquireExclusivePrefixLock(transactionId, prefixKey, expiresMs, durability, cancellationToken, coordinatorKey, operationId);
        public virtual Task<(KeyValueResponseType, HLCTimestamp HolderTransactionId)> LocateAndTryAcquireRangeLock(HLCTimestamp transactionId, string prefix, string? startKey, bool startInclusive, string? endKey, bool endInclusive, int expiresMs, KeyValueDurability durability, RangeLockMode mode, CancellationToken cancellationToken, string coordinatorKey = "", TransactionOperationId operationId = default) => inner.LocateAndTryAcquireRangeLock(transactionId, prefix, startKey, startInclusive, endKey, endInclusive, expiresMs, durability, mode, cancellationToken, coordinatorKey, operationId);
        public virtual Task<(KeyValueResponseType, HLCTimestamp HolderTransactionId)> LocateAndTryAcquireExclusiveRangeLock(HLCTimestamp transactionId, string prefix, string? startKey, bool startInclusive, string? endKey, bool endInclusive, int expiresMs, KeyValueDurability durability, CancellationToken cancellationToken) => inner.LocateAndTryAcquireExclusiveRangeLock(transactionId, prefix, startKey, startInclusive, endKey, endInclusive, expiresMs, durability, cancellationToken);
        public virtual Task<List<(KeyValueResponseType, string, KeyValueDurability, HLCTimestamp HolderTransactionId)>> LocateAndTryAcquireManyExclusiveLocks(HLCTimestamp transactionId, List<(string key, int expiresMs, KeyValueDurability durability)> keys, CancellationToken cancellationToken, string coordinatorKey = "", TransactionOperationId operationId = default) => inner.LocateAndTryAcquireManyExclusiveLocks(transactionId, keys, cancellationToken, coordinatorKey, operationId);
        public virtual Task<(KeyValueResponseType, string)> LocateAndTryReleaseExclusiveLock(HLCTimestamp transactionId, string key, KeyValueDurability durability, CancellationToken cancellationToken, string coordinatorKey = "", TransactionOperationId operationId = default) => inner.LocateAndTryReleaseExclusiveLock(transactionId, key, durability, cancellationToken, coordinatorKey, operationId);
        public virtual Task<KeyValueResponseType> LocateAndTryReleaseExclusivePrefixLock(HLCTimestamp transactionId, string prefixKey, KeyValueDurability durability, CancellationToken cancellationToken, string coordinatorKey = "", TransactionOperationId operationId = default) => inner.LocateAndTryReleaseExclusivePrefixLock(transactionId, prefixKey, durability, cancellationToken, coordinatorKey, operationId);
        public virtual Task<KeyValueResponseType> LocateAndTryReleaseExclusiveRangeLock(HLCTimestamp transactionId, string prefix, string? startKey, bool startInclusive, string? endKey, bool endInclusive, KeyValueDurability durability, CancellationToken cancellationToken, string coordinatorKey = "", TransactionOperationId operationId = default) => inner.LocateAndTryReleaseExclusiveRangeLock(transactionId, prefix, startKey, startInclusive, endKey, endInclusive, durability, cancellationToken, coordinatorKey, operationId);
        public virtual Task<List<(KeyValueResponseType, string, KeyValueDurability)>> LocateAndTryReleaseManyExclusiveLocks(HLCTimestamp transactionId, List<(string key, KeyValueDurability durability)> keys, CancellationToken cancellationToken) => inner.LocateAndTryReleaseManyExclusiveLocks(transactionId, keys, cancellationToken);
        public virtual Task<(KeyValueResponseType, HLCTimestamp, string, KeyValueDurability)> LocateAndTryPrepareMutations(HLCTimestamp transactionId, HLCTimestamp commitId, string key, KeyValueDurability durability, CancellationToken cancellationToken, long routedGeneration = 0, string? recordAnchorKey = null) => inner.LocateAndTryPrepareMutations(transactionId, commitId, key, durability, cancellationToken, routedGeneration, recordAnchorKey);
        public virtual Task<List<(KeyValueResponseType, HLCTimestamp, string, KeyValueDurability)>> LocateAndTryPrepareManyMutations(HLCTimestamp transactionId, HLCTimestamp commitId, List<(string key, KeyValueDurability durability)> keys, CancellationToken cancellationToken, string? recordAnchorKey = null) => inner.LocateAndTryPrepareManyMutations(transactionId, commitId, keys, cancellationToken, recordAnchorKey);
        public virtual Task<(KeyValueResponseType, long)> LocateAndTryCommitMutations(HLCTimestamp transactionId, string key, HLCTimestamp ticketId, KeyValueDurability durability, CancellationToken cancellationToken) => inner.LocateAndTryCommitMutations(transactionId, key, ticketId, durability, cancellationToken);
        public virtual Task<List<(KeyValueResponseType, string, long, KeyValueDurability)>> LocateAndTryCommitManyMutations(HLCTimestamp transactionId, List<(string key, HLCTimestamp ticketId, KeyValueDurability durability)> keys, CancellationToken cancellationToken) => inner.LocateAndTryCommitManyMutations(transactionId, keys, cancellationToken);
        public virtual Task<(KeyValueResponseType, long)> LocateAndTryRollbackMutations(HLCTimestamp transactionId, string key, HLCTimestamp ticketId, KeyValueDurability durability, CancellationToken cancellationToken) => inner.LocateAndTryRollbackMutations(transactionId, key, ticketId, durability, cancellationToken);
        public virtual Task<List<(KeyValueResponseType, string, long, KeyValueDurability)>> LocateAndTryRollbackManyMutations(HLCTimestamp transactionId, List<(string key, HLCTimestamp ticketId, KeyValueDurability durability)> keys, CancellationToken cancellationToken) => inner.LocateAndTryRollbackManyMutations(transactionId, keys, cancellationToken);
        public virtual Task<(KeyValueResponseType, TransactionHandle)> LocateAndStartTransaction(KeyValueTransactionOptions options, CancellationToken cancellationToken) => inner.LocateAndStartTransaction(options, cancellationToken);
        public virtual Task<(KeyValueResponseType, string?)> LocateAndCommitTransaction(TransactionHandle handle, CancellationToken cancellationToken) => inner.LocateAndCommitTransaction(handle, cancellationToken);
        public virtual Task<KeyValueResponseType> LocateAndRollbackTransaction(TransactionHandle handle, CancellationToken cancellationToken) => inner.LocateAndRollbackTransaction(handle, cancellationToken);
        public virtual Task<(OperationRegistrationOutcome outcome, KeyValueResponseType cachedType, long cachedRevision, HLCTimestamp cachedTimestamp, string? recordAnchorKey)> LocateAndBeginOperation(string coordinatorKey, HLCTimestamp transactionId, TransactionOperationId operationId, OperationKind kind, byte[]? payloadDigest, CancellationToken cancellationToken) => inner.LocateAndBeginOperation(coordinatorKey, transactionId, operationId, kind, payloadDigest, cancellationToken);
        public virtual Task<(KeyValueResponseType outcome, string? anchor)> LocateAndCompleteOperation(string coordinatorKey, HLCTimestamp transactionId, TransactionOperationId operationId, OperationCompletionPayload payload, CancellationToken cancellationToken) => inner.LocateAndCompleteOperation(coordinatorKey, transactionId, operationId, payload, cancellationToken);
        public virtual Task<(KeyValueResponseType outcome, string? anchor)> CompleteOperationInbound(string coordinatorKey, HLCTimestamp transactionId, TransactionOperationId operationId, OperationCompletionPayload payload) => inner.CompleteOperationInbound(coordinatorKey, transactionId, operationId, payload);
        public virtual (OperationRegistrationOutcome outcome, KeyValueResponseType cachedType, long cachedRevision, HLCTimestamp cachedTimestamp, string? recordAnchorKey) BeginOperation(HLCTimestamp transactionId, TransactionOperationId operationId, OperationKind kind, byte[]? payloadDigest) => inner.BeginOperation(transactionId, operationId, kind, payloadDigest);
        public virtual string? CompleteOperation(HLCTimestamp transactionId, TransactionOperationId operationId, OperationCompletionPayload payload) => inner.CompleteOperation(transactionId, operationId, payload);
        public virtual Task<TransactionWorkingSet?> LocateAndGetTransactionWorkingSet(string coordinatorKey, HLCTimestamp transactionId, CancellationToken cancellationToken) => inner.LocateAndGetTransactionWorkingSet(coordinatorKey, transactionId, cancellationToken);
        public virtual Task<(KeyValueResponseType, TransactionWorkingSet?)> LocateAndCloseTransaction(string coordinatorKey, HLCTimestamp transactionId, CancellationToken cancellationToken) => inner.LocateAndCloseTransaction(coordinatorKey, transactionId, cancellationToken);
        public virtual TransactionWorkingSet? GetTransactionWorkingSet(HLCTimestamp transactionId) => inner.GetTransactionWorkingSet(transactionId);
        public virtual Task<(KeyValueResponseType, TransactionWorkingSet?)> CloseTransaction(HLCTimestamp transactionId, CancellationToken cancellationToken) => inner.CloseTransaction(transactionId, cancellationToken);
        public virtual Task<(KeyValueResponseType, string, KeyValueDurability, HLCTimestamp HolderTransactionId)> TryAcquireExclusiveLock(HLCTimestamp transactionId, string key, int expiresMs, KeyValueDurability durability) => inner.TryAcquireExclusiveLock(transactionId, key, expiresMs, durability);
        public virtual Task<KeyValueResponseType> TryAcquireExclusivePrefixLock(HLCTimestamp transactionId, string prefixKey, int expiresMs, KeyValueDurability durability) => inner.TryAcquireExclusivePrefixLock(transactionId, prefixKey, expiresMs, durability);
        public virtual Task<(KeyValueResponseType, HLCTimestamp HolderTransactionId)> TryAcquireRangeLock(HLCTimestamp transactionId, string prefix, string? startKey, bool startInclusive, string? endKey, bool endInclusive, int expiresMs, KeyValueDurability durability, RangeLockMode mode) => inner.TryAcquireRangeLock(transactionId, prefix, startKey, startInclusive, endKey, endInclusive, expiresMs, durability, mode);
        public virtual Task<(KeyValueResponseType, HLCTimestamp HolderTransactionId)> TryAcquireExclusiveRangeLock(HLCTimestamp transactionId, string prefix, string? startKey, bool startInclusive, string? endKey, bool endInclusive, int expiresMs, KeyValueDurability durability) => inner.TryAcquireExclusiveRangeLock(transactionId, prefix, startKey, startInclusive, endKey, endInclusive, expiresMs, durability);
        public virtual Task<List<KeyValueRangeLock>> GetRangeLocks(string keySpace) => inner.GetRangeLocks(keySpace);
        public virtual Task ImportRangeLocks(string keySpace, List<KeyValueRangeLock> locks) => inner.ImportRangeLocks(keySpace, locks);
        public virtual Task ImportCompletionReceipts(IReadOnlyCollection<CompletionReceiptRecord> receipts) => inner.ImportCompletionReceipts(receipts);
        public virtual Task<bool> ImportCompletionReceiptsReplicated(int partitionId, IReadOnlyCollection<CompletionReceiptRecord> receipts) => inner.ImportCompletionReceiptsReplicated(partitionId, receipts);
        public virtual Task<bool> ForgetCompletionReceiptsReplicated(int partitionId, IReadOnlyCollection<CompletionReceiptRecord> receipts) => inner.ForgetCompletionReceiptsReplicated(partitionId, receipts);
        public virtual Task<bool> DurableOperationLocal(int partitionId, int kind, string logType, byte[] payload, CancellationToken cancellationToken) => inner.DurableOperationLocal(partitionId, kind, logType, payload, cancellationToken);
        public virtual Task<byte[]?> LookupTransactionRecordLocal(int partitionId, HLCTimestamp transactionId, long epoch, string anchorKey, CancellationToken cancellationToken) => inner.LookupTransactionRecordLocal(partitionId, transactionId, epoch, anchorKey, cancellationToken);
        public virtual Task<(KeyValueResponseType, string)> TryReleaseExclusiveLock(HLCTimestamp transactionId, string key, KeyValueDurability durability) => inner.TryReleaseExclusiveLock(transactionId, key, durability);
        public virtual Task<KeyValueResponseType> TryReleaseExclusivePrefixLock(HLCTimestamp transactionId, string prefixKey, KeyValueDurability durability) => inner.TryReleaseExclusivePrefixLock(transactionId, prefixKey, durability);
        public virtual Task<KeyValueResponseType> TryReleaseExclusiveRangeLock(HLCTimestamp transactionId, string prefix, string? startKey, bool startInclusive, string? endKey, bool endInclusive, KeyValueDurability durability) => inner.TryReleaseExclusiveRangeLock(transactionId, prefix, startKey, startInclusive, endKey, endInclusive, durability);
        public virtual Task<(KeyValueResponseType, HLCTimestamp, string, KeyValueDurability)> TryPrepareMutations(HLCTimestamp transactionId, HLCTimestamp commitId, string key, KeyValueDurability durability, long routedGeneration = 0, string? recordAnchorKey = null) => inner.TryPrepareMutations(transactionId, commitId, key, durability, routedGeneration, recordAnchorKey);
        public virtual Task<(KeyValueResponseType, long)> TryCommitMutations(HLCTimestamp transactionId, string key, HLCTimestamp proposalTicketId, KeyValueDurability durability) => inner.TryCommitMutations(transactionId, key, proposalTicketId, durability);
        public virtual Task<(KeyValueResponseType, long)> TryRollbackMutations(HLCTimestamp transactionId, string key, HLCTimestamp proposalTicketId, KeyValueDurability durability) => inner.TryRollbackMutations(transactionId, key, proposalTicketId, durability);
        public virtual Task<KeyValueTransactionResult> TryExecuteTransactionScript(ReadOnlyMemory<byte> script, string? hash, List<KeyValueParameter>? parameters, TransactionPriority priority = TransactionPriority.Normal) => inner.TryExecuteTransactionScript(script, hash, parameters, priority);
        public virtual Task<KeyValueGetByBucketResult> GetByBucket(HLCTimestamp transactionId, string prefixKeyName, HLCTimestamp readTimestamp, KeyValueDurability durability) => inner.GetByBucket(transactionId, prefixKeyName, readTimestamp, durability);
        public virtual Task<KeyValueGetByBucketResult> ScanByPrefix(string prefixKeyName, HLCTimestamp readTimestamp, KeyValueDurability durability, bool includeTombstones = false) => inner.ScanByPrefix(prefixKeyName, readTimestamp, durability, includeTombstones);
        public virtual Task<KeyValueGetByBucketResult> ScanAllByPrefix(string prefixKeyName, HLCTimestamp readTimestamp, KeyValueDurability durability, CancellationToken cancellationToken) => inner.ScanAllByPrefix(prefixKeyName, readTimestamp, durability, cancellationToken);
        public virtual Task<(KeyValueResponseType, TransactionHandle)> StartTransaction(KeyValueTransactionOptions options) => inner.StartTransaction(options);
        public virtual Task<(KeyValueResponseType, string?)> CommitTransaction(TransactionHandle handle) => inner.CommitTransaction(handle);
        public virtual Task<KeyValueResponseType> RollbackTransaction(TransactionHandle handle) => inner.RollbackTransaction(handle);
        public virtual Task<(SequenceResponseType, ReadOnlySequenceEntry?)> LocateAndGetSequence(string name, SequenceDurability durability, CancellationToken cancellationToken) => inner.LocateAndGetSequence(name, durability, cancellationToken);
        public virtual Task<(SequenceResponseType, long)> LocateAndCreateSequence(string name, long initialValue, long increment, long? maxValue, SequenceDurability durability, CancellationToken cancellationToken) => inner.LocateAndCreateSequence(name, initialValue, increment, maxValue, durability, cancellationToken);
        public virtual Task<(SequenceResponseType, SequenceAllocation)> LocateAndNextSequenceValue(string name, string? idempotencyKey, SequenceDurability durability, CancellationToken cancellationToken) => inner.LocateAndNextSequenceValue(name, idempotencyKey, durability, cancellationToken);
        public virtual Task<(SequenceResponseType, SequenceAllocation)> LocateAndReserveSequenceRange(string name, int count, string? idempotencyKey, SequenceDurability durability, CancellationToken cancellationToken) => inner.LocateAndReserveSequenceRange(name, count, idempotencyKey, durability, cancellationToken);
        public virtual Task<SequenceResponseType> LocateAndDeleteSequence(string name, SequenceDurability durability, CancellationToken cancellationToken) => inner.LocateAndDeleteSequence(name, durability, cancellationToken);
        public virtual Task<(SequenceResponseType, ReadOnlySequenceEntry?)> GetSequence(string name, SequenceDurability durability, CancellationToken cancellationToken) => inner.GetSequence(name, durability, cancellationToken);
        public virtual Task<(SequenceResponseType, long)> CreateSequence(string name, long initialValue, long increment, long? maxValue, SequenceDurability durability, CancellationToken cancellationToken) => inner.CreateSequence(name, initialValue, increment, maxValue, durability, cancellationToken);
        public virtual Task<(SequenceResponseType, SequenceAllocation)> NextSequenceValue(string name, string? idempotencyKey, SequenceDurability durability, CancellationToken cancellationToken) => inner.NextSequenceValue(name, idempotencyKey, durability, cancellationToken);
        public virtual Task<(SequenceResponseType, SequenceAllocation)> ReserveSequenceRange(string name, int count, string? idempotencyKey, SequenceDurability durability, CancellationToken cancellationToken) => inner.ReserveSequenceRange(name, count, idempotencyKey, durability, cancellationToken);
        public virtual Task<SequenceResponseType> DeleteSequence(string name, SequenceDurability durability, CancellationToken cancellationToken) => inner.DeleteSequence(name, durability, cancellationToken);
        public virtual Task<bool> OnLogRestored(int partitionId, RaftLog log) => inner.OnLogRestored(partitionId, log);
        public virtual Task<bool> OnReplicationReceived(int partitionId, RaftLog log) => inner.OnReplicationReceived(partitionId, log);
        public virtual void OnReplicationError(int partitionId, RaftLog log) => inner.OnReplicationError(partitionId, log);
        public virtual Task<bool> OnLeaderChanged(int partitionId, string node) => inner.OnLeaderChanged(partitionId, node);
        public virtual Task FlushPersistenceAsync() => inner.FlushPersistenceAsync();
        public virtual Task BootstrapFromPitrBackupAsync(string backupDir, Guid leafBackupId, HLCTimestamp targetTime, IWAL walAdapter, TimeSpan pitrWindow, TimeSpan baseSnapshotInterval) => inner.BootstrapFromPitrBackupAsync(backupDir, leafBackupId, targetTime, walAdapter, pitrWindow, baseSnapshotInterval);
        public virtual void RegisterKeyRange(string keySpace) => inner.RegisterKeyRange(keySpace);
        public virtual Task<bool> RegisterKeyRangeAsync(string keySpace, CancellationToken cancellationToken = default) => inner.RegisterKeyRangeAsync(keySpace, cancellationToken);
        public virtual Task<bool> RemoveKeyRangeAsync(string keySpace, CancellationToken cancellationToken = default) => inner.RemoveKeyRangeAsync(keySpace, cancellationToken);
        public virtual Task<int> TriggerAutoSplitAsync(CancellationToken ct = default) => inner.TriggerAutoSplitAsync(ct);
        public virtual Task<int> TriggerAutoMergeAsync(CancellationToken ct = default) => inner.TriggerAutoMergeAsync(ct);
        public virtual bool IsBackupConfigured => inner.IsBackupConfigured;
        public virtual bool IsRemoteRestoreAllowed => inner.IsRemoteRestoreAllowed;
        public virtual Task<KahunaBackupGcResult> RunBackupGarbageCollectionAsync(bool dryRun, CancellationToken ct = default) => inner.RunBackupGarbageCollectionAsync(dryRun, ct);
        public virtual Task<KahunaBackupInfo> TakeFullBackupAsync(CancellationToken ct = default) => inner.TakeFullBackupAsync(ct);
        public virtual Task<KahunaBackupInfo> TakeIncrementalBackupAsync(Guid parentBackupId, CancellationToken ct = default) => inner.TakeIncrementalBackupAsync(parentBackupId, ct);
        public virtual Task<KahunaBackupInfo> TakeCoordinatedBackupAsync(CancellationToken ct = default) => inner.TakeCoordinatedBackupAsync(ct);
        public virtual Task<IReadOnlyList<KahunaBackupInfo>> ListBackupsAsync(CancellationToken ct = default) => inner.ListBackupsAsync(ct);
        public virtual Task<IReadOnlyList<KahunaBackupInfo>> GetBackupChainAsync(Guid leafBackupId, CancellationToken ct = default) => inner.GetBackupChainAsync(leafBackupId, ct);
        public virtual Task<KahunaRestoreResponse> RestoreToAsync(Guid leafBackupId, string targetDir, long targetTimeMs, CancellationToken ct = default) => inner.RestoreToAsync(leafBackupId, targetDir, targetTimeMs, ct);
        public virtual Task<(KeyValueResponseType Type, string HoldId, HLCTimestamp LeaseExpiry)> LocateAndAcquireSnapshotHold(string holderId, HLCTimestamp timestamp, int leaseMs, CancellationToken ct) => inner.LocateAndAcquireSnapshotHold(holderId, timestamp, leaseMs, ct);
        public virtual Task<(KeyValueResponseType Type, HLCTimestamp LeaseExpiry)> LocateAndRenewSnapshotHold(string holdId, int leaseMs, CancellationToken ct) => inner.LocateAndRenewSnapshotHold(holdId, leaseMs, ct);
        public virtual Task<KeyValueResponseType> LocateAndReleaseSnapshotHold(string holdId, CancellationToken ct) => inner.LocateAndReleaseSnapshotHold(holdId, ct);
        public virtual Task<(KeyValueResponseType Type, HLCTimestamp EffectiveFloor, int LiveHolds)> GetSnapshotFloor(CancellationToken ct) => inner.GetSnapshotFloor(ct);
}
