
/**
 * This file is part of CamusDB
 *
 * For the full copyright and license information, please view the LICENSE.txt
 * file that was distributed with this source code.
 */

namespace CamusDB.Core.CommandsExecutor.Models;

public enum ColumnConstraintType
{
    PrimaryKey,
    Null,
    NotNull,
    Unique,
    Default,
    DefaultFunction,
    Check,
    ForeignKey,

    /// <summary>
    /// Inline <c>COMMENT '&lt;text&gt;'</c> on a column definition. The decoded text is carried as a
    /// String <c>ColumnValue</c>, so a present-but-empty comment stays distinguishable from an absent
    /// one (which produces no entry at all).
    /// </summary>
    Comment,

    /// <summary>
    /// Inline <c>STORAGE &lt;strategy&gt;</c> on a column definition. The strategy name is carried as a
    /// String <c>ColumnValue</c> and parsed by the creator, which also rejects it on a column type that
    /// has no variable-length value.
    /// </summary>
    Storage,

    /// <summary>
    /// <c>SERIAL</c>, <c>GENERATED ALWAYS AS IDENTITY</c> or <c>GENERATED BY DEFAULT AS IDENTITY</c>.
    /// The value carries the word <c>always</c> or <c>bydefault</c>, which is the only thing the
    /// two spellings differ in.
    /// </summary>
    Identity,

    /// <summary>
    /// <c>DEFAULT nextval('&lt;name&gt;')</c>. The value carries the sequence's <b>name</b>, because
    /// the parser has no schema to resolve it against; the DDL path turns it into the sequence's
    /// immutable id, which is what the column stores.
    /// </summary>
    DefaultSequence

}
