/**
 * This file is part of CamusDB
 *
 * For the full copyright and license information, please view the LICENSE.txt
 * file that was distributed with this source code.
 */

namespace CamusDB.Core.CommandsExecutor.Models;

/// <summary>
/// How a column declared as an identity column treats a value the caller supplies for it. The two
/// spellings differ in nothing else, so this difference is the whole reason both exist.
///
/// <para>Carried only between the parser and the DDL path, which turns it into a sequence plus a
/// column default. Nothing persists this enum: the schema records the owned sequence's id and the
/// <c>ALWAYS</c> flag instead.</para>
/// </summary>
public enum ColumnIdentityKind
{
    /// <summary>
    /// <c>GENERATED BY DEFAULT AS IDENTITY</c>, and what <c>SERIAL</c> desugars to. A supplied
    /// value is accepted and written; the sequence supplies one only when the column is omitted.
    /// </summary>
    ByDefault,

    /// <summary>
    /// <c>GENERATED ALWAYS AS IDENTITY</c>. A supplied value is refused, so the column's values
    /// can only ever come from its sequence.
    /// </summary>
    Always,
}
