language: csharp
mono: none
dotnet: 6.0

dist: focal
sudo: false

git:
  depth: 2

script:
  - (cd CamusDB.Tests && dotnet test)

cache:
  apt: true
  timeout: 691200
  directories:
    - .nuget/packages
