
/**
 * This file is part of CamusDB  
 *
 * For the full copyright and license information, please view the LICENSE.txt
 * file that was distributed with this source code.
 */

using CamusDB.Core.Catalogs.Models;
using CamusDB.Core.Catalogs.Apply;
using CamusDB.Core.Catalogs.Meta;
using CamusDB.Core.Catalogs.Replication;
using CamusDB.Core.CommandsExecutor.Models;
using CamusDB.Core.CommandsExecutor.Models.Tickets;
using CamusDB.Core.SQLParser;
using CamusDB.Core.Serializer;
using CamusDB.Core.Storage.Kv;
using CamusDB.Core.Transactions;
using CamusDB.Core.Util.ObjectIds;
using Kahuna;
using Kahuna.Server.KeyValues;
using Kahuna.Shared.KeyValue;
using Kommander.Time;
using Microsoft.Extensions.Logging;
using System.Text.Json;

namespace CamusDB.Core.Catalogs;

/// <summary>
/// Maintains references to all objects in the database.
/// Allows knowing the description and characteristics of tables, views, indexes, etc.
/// </summary>
public sealed class CatalogsManager
{
    private readonly ILogger<ICamusDB> logger;

    private readonly SchemaCheckpointWriter checkpoints;

    private readonly SchemaChangePublisher publisher;

    /// <summary>
    /// Test hook, written through to <see cref="SchemaCheckpointWriter"/>: when non-null, every
    /// checkpoint persist throws it instead of writing, so a test can drive the exhausted-retry path
    /// without a real KV fault. Kept on the facade because that is where the tests reach it.
    /// </summary>
    internal Exception? TestPersistCheckpointException {
        get => checkpoints.TestPersistCheckpointException;
        set => checkpoints.TestPersistCheckpointException = value;
    }

    public CatalogsManager(ILogger<ICamusDB> logger)
    {
        this.logger = logger;

        checkpoints = new(logger);
        publisher = new(checkpoints, logger);
    }

    /// <summary>
    /// Adds a new table object to the database schema as well as its indexes.
    /// <paramref name="tableId"/> is the pre-allocated, globally-unique id for the new table,
    /// produced by the proposer via <see cref="DatabaseRegistry.AllocateTableIdAsync"/> before
    /// this method is called. It is carried verbatim in the replicated payload so every node
    /// applies the same id; the caller is responsible for ensuring it was not generated by
    /// a follower.
    /// </summary>
    /// <exception cref="CamusDBException"></exception>
    public Task<TableSchema> CreateTable(DatabaseDescriptor database, CreateTableTicket ticket, KvTransaction tx, string tableId)
        => CreateTableReplicatedAsync(database, ticket, tx, tableId);

    /// <summary>
    /// Modifies an existing table object allowing to add or remove columns.
    /// </summary>
    /// <param name="database"></param>
    /// <param name="ticket"></param>
    /// <returns></returns>
    /// <exception cref="CamusDBException"></exception>
    public Task<TableSchema> AlterTable(DatabaseDescriptor database, AlterColumnTicket ticket, KvTransaction tx)
        => AlterTableReplicatedAsync(database, ticket, tx);

    /// <summary>
    /// Removes a table from the live schema via a replicated <see cref="SchemaOp.DropTable"/> delta.
    /// When <paramref name="deferred"/> is <c>true</c> the drop is recoverable: the schema checkpoint
    /// that deletes the per-table meta key also writes the table's orphan record in the same
    /// transaction (see <see cref="PersistDroppedTableAsync"/>), so a crash can never detach the table
    /// without leaving a recovery record. The caller must have already retained the row/index data.
    /// </summary>
    public Task<TableSchema?> DropTableSchema(DatabaseDescriptor database, string tableName, string tableId, KvTransaction tx, bool deferred = false)
        => DropTableReplicatedAsync(database, tableName, tx, deferred);

    /// <summary>
    /// Allows querying the current schema of a table object.
    /// </summary>
    /// <param name="database"></param>
    /// <param name="tableName"></param>
    /// <returns></returns>
    /// <exception cref="CamusDBException"></exception>
    public TableSchema GetTableSchema(DatabaseDescriptor database, string tableName) // @todo return a snapshot instead of the schema
    {
        if (database.Schema.Tables.TryGetValue(tableName, out TableSchema? tableSchema))
            return tableSchema;

        throw new CamusDBException(CamusDBErrorCodes.TableDoesntExist, $"Table '{tableName}' doesn't exist");
    }

    /// <summary>
    /// Returns true if a table exists
    /// </summary>
    /// <param name="database"></param>
    /// <param name="tableName"></param>
    /// <returns></returns>
    public bool TableExists(DatabaseDescriptor database, string tableName)
    {
        return database.Schema.Tables.ContainsKey(tableName);
    }

    private async Task<TableSchema> CreateTableReplicatedAsync(DatabaseDescriptor database, CreateTableTicket ticket, KvTransaction tx, string tableId)
    {
        SchemaChangeLogEntry entry;

        await database.Schema.AcquireLockAsync().ConfigureAwait(false);
        try
        {
            entry = SchemaChangeEntryFactory.CreateTableEntry(database, ticket, tx, tableId);
            SchemaDeltaApplier.ValidateSchemaDelta(database, entry);
        }
        finally
        {
            database.Schema.ReleaseLock();
        }

        await publisher.ReplicateAndWaitLocalApplyAsync(database, entry).ConfigureAwait(false);
        return GetTableSchema(database, ticket.TableName);
    }

    private async Task<TableSchema> AlterTableReplicatedAsync(DatabaseDescriptor database, AlterColumnTicket ticket, KvTransaction tx)
    {
        SchemaChangeLogEntry entry;

        await database.Schema.AcquireLockAsync().ConfigureAwait(false);
        try
        {
            entry = SchemaChangeEntryFactory.AlterTableEntry(database, ticket, tx);
            SchemaDeltaApplier.ValidateSchemaDelta(database, entry);
        }
        finally
        {
            database.Schema.ReleaseLock();
        }

        await publisher.ReplicateAndWaitLocalApplyAsync(database, entry).ConfigureAwait(false);
        return GetTableSchema(database, ticket.TableName);
    }

    private async Task<TableSchema?> DropTableReplicatedAsync(DatabaseDescriptor database, string tableName, KvTransaction tx, bool deferred)
    {
        SchemaChangeLogEntry entry;

        await database.Schema.AcquireLockAsync().ConfigureAwait(false);
        try
        {
            entry = SchemaChangeEntryFactory.DropTableEntry(database, tableName, tx, deferred);
            SchemaDeltaApplier.ValidateSchemaDelta(database, entry);
        }
        finally
        {
            database.Schema.ReleaseLock();
        }

        await publisher.ReplicateAndWaitLocalApplyAsync(database, entry).ConfigureAwait(false);
        return null;
    }

    /// <summary>
    /// Reattaches an orphaned (deferred-dropped) table to the live schema under <paramref name="newName"/>,
    /// reusing its preserved id so it reads its retained rows and index entries. Modeled as a dedicated
    /// <see cref="SchemaOp.RelinkTable"/> delta rebuilt from the orphan's captured schema — preserving the
    /// original table id, column ids, index definitions, check constraints, <b>and schema version</b> — so
    /// every node reconstructs an identical table and rows written under the drop-time version decode
    /// correctly. The apply configures a lazy schema-history loader against the retained
    /// <c>{dbId}/meta/history:{tableId}:*</c> keys, so rows written under earlier pre-<c>ALTER</c> versions
    /// also decode (immediately and after reopen). The orphan record is removed in the caller's DDL
    /// transaction after the reattach is applied.
    ///
    /// <para><b>Ordering:</b> reattach-then-delete-orphan, mirroring database relink. A crash after the
    /// reattach but before the orphan-record delete commits leaves a live table with a stale orphan
    /// record; the garbage collector skips orphan records whose table exists in the live schema.</para>
    /// </summary>
    public async Task<TableSchema> RelinkTable(DatabaseDescriptor database, OrphanTableRecord orphan, string newName, KvTransaction tx)
    {
        SchemaChangeLogEntry entry;

        await database.Schema.AcquireLockAsync().ConfigureAwait(false);
        try
        {
            entry = SchemaChangeEntryFactory.RelinkTableEntry(database, orphan, newName, tx);
            SchemaDeltaApplier.ValidateSchemaDelta(database, entry);
        }
        finally
        {
            database.Schema.ReleaseLock();
        }

        await publisher.ReplicateAndWaitLocalApplyAsync(database, entry).ConfigureAwait(false);

        TableSchema reattached = GetTableSchema(database, newName);

        // Restore the system-schema table object and persist it in the DDL transaction, mirroring
        // TableCreator (deferred drop removed it). Without this the live schema has the table but the
        // system schema does not, an asymmetry with the create/drop paths.
        RegisterTableSystemObject(database, reattached);
        await PersistSystemMetaAsync(database, tx).ConfigureAwait(false);

        // The table is live again — drop the orphan record so the GC leaves the reattached data alone.
        await DeleteTableOrphanAsync(database, orphan.TableId, tx).ConfigureAwait(false);

        return reattached;
    }

    /// <summary>
    /// Publishes a retired contents generation as a <b>new</b> relation, so the rows a
    /// <c>TRUNCATE</c> made unreachable can be read again.
    /// </summary>
    /// <remarks>
    /// <para><b>A fresh logical id is mandatory.</b> The retired key-space is named by a storage id,
    /// and on a relation's first truncate that storage id <em>is</em> the still-live source relation's
    /// id. Reusing it would publish a second relation under an id that is already live — two names for
    /// one identity, with the grants and dependencies of the source silently attached to the recovery.
    /// The recovered relation therefore gets a new id and points at the retired key-space through
    /// <see cref="TableSchema.StorageId"/>, which is exactly the separation that made the truncate
    /// cheap in the first place.</para>
    ///
    /// <para>The captured column layouts are copied under the new id because the retained rows carry
    /// the source relation's schema versions, and the append-only history keys that describe those
    /// versions live under the source's id — where the recovered relation cannot reach them.</para>
    ///
    /// <para>Order is reattach, then delete the record. A crash in between leaves a live relation with
    /// a stale record; the collector recognises that from <see cref="OrphanTableRecord.RelinkTargetId"/>
    /// and removes the record without touching the storage the recovery now owns.</para>
    /// </remarks>
    public async Task<TableSchema> RelinkRetiredContents(
        DatabaseDescriptor database, OrphanTableRecord orphan, string newTableId, string newName, KvTransaction tx)
    {
        TableSchema captured = orphan.Schema;

        OrphanTableRecord published = new()
        {
            Kind = orphan.Kind,
            TableId = newTableId,
            FormerName = orphan.FormerName,
            DroppedAt = orphan.DroppedAt,
            SourceTableId = orphan.SourceTableId,
            RetiredStorageId = orphan.RetiredStorageId,
            RelinkTargetId = newTableId,
            Schema = new()
            {
                Id = newTableId,
                // The recovered relation reads the retired key-space; its own id names nothing on disk.
                StorageId = orphan.RetiredStorageId,
                Version = captured.Version,
                Name = newName,
                Columns = captured.Columns,
                Indexes = captured.Indexes,
                CheckConstraints = captured.CheckConstraints,
                Settings = captured.Settings,
                Comment = captured.Comment,
                Kind = captured.Kind,
                ViewDefinition = captured.ViewDefinition,
                IsPopulated = captured.IsPopulated,
                RefreshedAt = captured.RefreshedAt,
            }
        };

        SchemaChangeLogEntry entry;

        await database.Schema.AcquireLockAsync().ConfigureAwait(false);
        try
        {
            entry = SchemaChangeEntryFactory.RelinkTableEntry(database, published, newName, tx);
            SchemaDeltaApplier.ValidateSchemaDelta(database, entry);
        }
        finally
        {
            database.Schema.ReleaseLock();
        }

        await publisher.ReplicateAndWaitLocalApplyAsync(database, entry).ConfigureAwait(false);

        TableSchema reattached = GetTableSchema(database, newName);

        RegisterTableSystemObject(database, reattached);
        await PersistSystemMetaAsync(database, tx).ConfigureAwait(false);

        // Copy the captured layouts under the new id so a row written under an older version of the
        // source relation still decodes through the recovered one.
        IKahuna kahuna = database.Kahuna.Kahuna;
        foreach (TableSchemaHistory history in captured.SchemaHistory ?? [])
        {
            byte[] historyBytes = MetaJsonSerializer.Serialize(history, MetaJsonContext.Default.TableSchemaHistory);
            await MetaKeyWriter.WriteMetaKey(kahuna, tx, MetaKeys.HistoryKey(database.Id, newTableId, history.Version), historyBytes).ConfigureAwait(false);
        }

        // Addressed by the key-space it protected, not by the relation that now owns it.
        await DeleteTableOrphanAsync(database, orphan.RetiredStorageId, tx).ConfigureAwait(false);

        return reattached;
    }

    /// <summary>
    /// Stamps a retired-contents record with the relation a recovery is about to publish, in its own
    /// committed transaction.
    /// </summary>
    /// <remarks>
    /// Written <b>before</b> the relation is published, so a crash between the two leaves evidence.
    /// Without it the collector cannot tell a recovery that half-finished from one that never started,
    /// and would purge the storage the half-finished recovery is about to hand back.
    /// </remarks>
    public async Task RecordRelinkTargetAsync(DatabaseDescriptor database, OrphanTableRecord orphan, string targetId)
    {
        orphan.RelinkTargetId = targetId;

        byte[] bytes = MetaJsonSerializer.Serialize(orphan, MetaJsonContext.Default.OrphanTableRecord);

        KvTransaction tx = await database.Transactions.BeginAsync(
            CamusIsolationLevel.ReadCommitted, CamusTransactionMode.ReadWrite
        ).ConfigureAwait(false);
        try
        {
            await MetaKeyWriter.WriteMetaKey(database.Kahuna.Kahuna, tx, MetaKeys.OrphanKey(database.Id, orphan.RetiredStorageId), bytes).ConfigureAwait(false);
            await database.Transactions.CommitAsync(tx).ConfigureAwait(false);
        }
        finally
        {
            await database.Transactions.RollbackIfNotCompletedAsync(tx).ConfigureAwait(false);
        }
    }

    /// <summary>
    /// Adds (or re-adds) the system-schema table object for <paramref name="tableSchema"/>, keyed by its
    /// immutable id. Shared by table creation and relink so both keep <c>SystemSchema.Tables</c> in sync
    /// with the live schema. In-memory only; the caller persists via <see cref="PersistSystemMetaAsync"/>.
    /// </summary>
    public void RegisterTableSystemObject(DatabaseDescriptor database, TableSchema tableSchema)
    {
        database.SystemSchemaSemaphore.Wait();
        try
        {
            database.SystemSchema.Tables.TryAdd(
                tableSchema.Id ?? "",
                new DatabaseTableObject(
                    type: DatabaseObjectType.Table,
                    id: tableSchema.Id ?? "",
                    name: tableSchema.Name!,
                    startOffset: ""));
        }
        finally
        {
            database.SystemSchemaSemaphore.Release();
        }
    }

    private async Task<bool> RenameTableReplicatedAsync(
        DatabaseDescriptor database, RenameTableTicket ticket, KvTransaction tx,
        Dictionary<string, ViewDefinition>? dependentViews)
    {
        SchemaChangeLogEntry entry;

        await database.Schema.AcquireLockAsync().ConfigureAwait(false);
        try
        {
            entry = SchemaChangeEntryFactory.RenameTableEntry(database, ticket, tx, dependentViews);
            SchemaDeltaApplier.ValidateSchemaDelta(database, entry);
        }
        finally
        {
            database.Schema.ReleaseLock();
        }

        await publisher.ReplicateAndWaitLocalApplyAsync(database, entry).ConfigureAwait(false);
        return true;
    }

    /// <param name="dependentViews">
    /// Rewritten bodies for the views that read this relation, applied in the same delta so no node
    /// ever observes a stale body — which, once the old name is free, can resolve to a different
    /// relation rather than fail. Null when nothing depends on it.
    /// </param>
    public Task<bool> RenameTable(
        DatabaseDescriptor database, RenameTableTicket ticket, KvTransaction tx,
        Dictionary<string, ViewDefinition>? dependentViews = null)
        => RenameTableReplicatedAsync(database, ticket, tx, dependentViews);

    public async Task<bool> RenameIndexInTableAsync(
        DatabaseDescriptor database,
        AlterIndexTicket ticket,
        KvTransaction tx
    )
    {
        string newName = ticket.NewName ?? throw new CamusDBException(CamusDBErrorCodes.InvalidInput, "NewName is required for RenameIndex");
        SchemaChangeLogEntry entry;

        await database.Schema.AcquireLockAsync().ConfigureAwait(false);
        try
        {
            entry = new()
            {
                Ts = tx.TransactionId,
                Database = database.Id,
                FromVersion = database.Schema.SchemaVersion,
                ToVersion = database.Schema.SchemaVersion + 1,
                Op = SchemaOp.RenameIndex,
                Payload = Serializator.Serialize(new SchemaRenamePayload
                {
                    TableName = ticket.TableName,
                    Kind = SchemaRenameKind.Index,
                    ElementName = ticket.IndexName,
                    NewName = newName
                })
            };

            SchemaDeltaApplier.ValidateSchemaDelta(database, entry);
        }
        finally
        {
            database.Schema.ReleaseLock();
        }

        await publisher.ReplicateAndWaitLocalApplyAsync(database, entry).ConfigureAwait(false);
        return true;
    }

    /// <summary>
    /// Replicates a completed AddIndex or DropIndex change to all cluster nodes via the
    /// schema log. Must be called AFTER the local work (backfill etc.) is done and
    /// <c>table.Schema.Indexes</c> reflects the final state. Only called when
    /// <c>isClusterMode</c>; standalone nodes need no replication.
    /// </summary>
    public async Task ReplicateIndexChangeAsync(
        DatabaseDescriptor database,
        AlterIndexTicket ticket,
        TableDescriptor table,
        KvTransaction tx
    )
    {
        SchemaChangeLogEntry entry;

        await database.Schema.AcquireLockAsync().ConfigureAwait(false);
        try
        {
            entry = ticket.Operation is AlterIndexOperation.DropIndex or AlterIndexOperation.DropPrimaryKey
                ? SchemaChangeEntryFactory.DropIndexEntry(database, ticket, tx)
                : SchemaChangeEntryFactory.AddIndexEntry(database, ticket, table, tx);
        }
        finally
        {
            database.Schema.ReleaseLock();
        }

        await publisher.ReplicateAndWaitLocalApplyAsync(database, entry).ConfigureAwait(false);
    }

    /// <summary>
    /// Proposes an <c>AddColumn</c> delta with <paramref name="initialState"/> and replicates
    /// it to all cluster nodes via the schema log.  Used by
    /// <see cref="SchemaChangeCoordinator"/> to begin a staged add sequence in
    /// <c>DeleteOnly</c> rather than jumping straight to <c>Public</c>.
    /// Only valid on cluster nodes (<c>isClusterMode</c>).
    /// </summary>
    public async Task ReplicateAddColumnInStateAsync(
        DatabaseDescriptor database,
        string tableName,
        ColumnInfo column,
        SchemaElementState initialState
    )
    {
        SchemaChangeLogEntry entry;

        await database.Schema.AcquireLockAsync().ConfigureAwait(false);
        try
        {
            entry = new()
            {
                Database = database.Id,
                FromVersion = database.Schema.SchemaVersion,
                ToVersion = database.Schema.SchemaVersion + 1,
                Op = SchemaOp.AddColumn,
                Payload = Serializator.Serialize(new SchemaAlterColumnPayload
                {
                    TableName = tableName,
                    // Built through FromColumnInfo, never field by field: a hand-copied list silently
                    // drops whatever it forgets, and MaxLength / ArrayElementType / Comment were all
                    // lost here while the single-node path kept them. Only Id and State are ours.
                    Column = SchemaChangeEntryFactory.SchemaColumnPayloadWithState(column, initialState)
                })
            };
            SchemaDeltaApplier.ValidateSchemaDelta(database, entry);
        }
        finally
        {
            database.Schema.ReleaseLock();
        }

        await publisher.ReplicateAndWaitLocalApplyAsync(database, entry).ConfigureAwait(false);
    }

    /// <summary>
    /// Proposes a single <c>SetElementState</c> delta and replicates it to all cluster nodes
    /// via the schema log, then waits for every live node to ack the resulting version.
    /// Validates the state transition before proposing.
    /// Only valid on cluster nodes (<c>isClusterMode</c>).
    /// </summary>
    public async Task ReplicateElementStateAsync(
        DatabaseDescriptor database,
        string tableName,
        string elementName,
        SchemaElementState targetState,
        SchemaElementKind elementKind = SchemaElementKind.Column
    )
    {
        SchemaChangeLogEntry entry;

        await database.Schema.AcquireLockAsync().ConfigureAwait(false);
        try
        {
            entry = new()
            {
                Database = database.Id,
                FromVersion = database.Schema.SchemaVersion,
                ToVersion = database.Schema.SchemaVersion + 1,
                Op = SchemaOp.SetElementState,
                Payload = Serializator.Serialize(new SchemaElementStatePayload
                {
                    TableName = tableName,
                    ElementName = elementName,
                    State = targetState,
                    ElementKind = elementKind,
                })
            };
            SchemaDeltaApplier.ValidateSchemaDelta(database, entry);
        }
        finally
        {
            database.Schema.ReleaseLock();
        }

        await publisher.ReplicateAndWaitLocalApplyAsync(database, entry).ConfigureAwait(false);
    }

    /// <summary>
    /// Proposes an <c>AddIndex</c> delta with <paramref name="initialState"/> and replicates
    /// it to all cluster nodes via the schema log. Used by <see cref="SchemaChangeCoordinator"/>
    /// to begin the staged add sequence in <c>DeleteOnly</c> rather than jumping straight to
    /// <c>Public</c>. Only valid on cluster nodes (<c>isClusterMode</c>).
    /// </summary>
    public async Task ReplicateAddIndexInStateAsync(
        DatabaseDescriptor database,
        string tableName,
        IndexBuildInfo indexBuildInfo,
        SchemaElementState initialState
    )
    {
        SchemaChangeLogEntry entry;

        await database.Schema.AcquireLockAsync().ConfigureAwait(false);
        try
        {
            entry = new()
            {
                Database = database.Id,
                FromVersion = database.Schema.SchemaVersion,
                ToVersion = database.Schema.SchemaVersion + 1,
                Op = SchemaOp.AddIndex,
                Payload = Serializator.Serialize(new SchemaIndexPayload
                {
                    TableName = tableName,
                    IndexName = indexBuildInfo.IndexName,
                    Index = new TableIndexSchema(
                        id: indexBuildInfo.IndexId,
                        name: indexBuildInfo.IndexName,
                        columnIds: indexBuildInfo.ColumnIds,
                        type: indexBuildInfo.IndexType,
                        state: initialState,
                        startOffset: null,
                        columnDirections: indexBuildInfo.ColumnDirections,
                        includeColumnIds: indexBuildInfo.IncludeColumnIds
                    )
                })
            };
            SchemaDeltaApplier.ValidateSchemaDelta(database, entry);
        }
        finally
        {
            database.Schema.ReleaseLock();
        }

        await publisher.ReplicateAndWaitLocalApplyAsync(database, entry).ConfigureAwait(false);
    }

    /// <summary>
    /// Proposes a <c>DropIndex</c> delta and replicates it to all cluster nodes.
    /// Used to compensate a failed coordinator-driven add-index sequence: if the
    /// index was added in <c>DeleteOnly</c> or <c>WriteOnly</c> state but the sequence
    /// did not reach <c>Public</c>, this removes it cleanly on every node.
    /// Only valid on cluster nodes (<c>isClusterMode</c>). No-op if the index is
    /// already absent (idempotent).
    /// </summary>
    public async Task ReplicateDropIndexAsync(DatabaseDescriptor database, string tableName, string indexName)
    {
        SchemaChangeLogEntry entry;

        await database.Schema.AcquireLockAsync().ConfigureAwait(false);
        try
        {
            entry = new()
            {
                Database = database.Id,
                FromVersion = database.Schema.SchemaVersion,
                ToVersion = database.Schema.SchemaVersion + 1,
                Op = SchemaOp.DropIndex,
                Payload = Serializator.Serialize(new SchemaIndexPayload
                {
                    TableName = tableName,
                    IndexName = indexName
                })
            };
            SchemaDeltaApplier.ValidateSchemaDelta(database, entry);
        }
        finally
        {
            database.Schema.ReleaseLock();
        }

        await publisher.ReplicateAndWaitLocalApplyAsync(database, entry).ConfigureAwait(false);
    }

    /// <summary>
    /// Proposes a <see cref="SchemaOp.SetTableSettings"/> delta and replicates it to all cluster nodes,
    /// so every node's in-memory <see cref="TableSchema.Settings"/> updates and the KV checkpoint is
    /// rewritten. Advances the database schema version (like check constraints) but not
    /// <see cref="TableSchema.Version"/> — settings do not affect row encoding.
    ///
    /// <para><b>Both modes use this path.</b> A standalone node is the only member of its own schema
    /// group, so proposing costs it a single-node commit and buys the same guarantees the cluster gets:
    /// the database schema version and the descriptor's head-version fence advance together, from the
    /// one place that advances them for every other schema operation. The earlier standalone shortcut
    /// wrote the table blob directly and left the version untouched, which made a background sweep that
    /// keys on the database schema version unable to notice a table's settings changing at all — TTL
    /// could be switched on and the sweep would never see it. Changing settings <em>is</em> a schema
    /// change; do not reintroduce a mode-specific path that pretends otherwise.</para>
    /// </summary>
    public async Task ReplicateSetTableSettingsAsync(
        DatabaseDescriptor database,
        string tableName,
        IReadOnlyDictionary<string, string> settings,
        IReadOnlyCollection<string>? removedKeys = null)
    {
        SchemaChangeLogEntry entry;

        await database.Schema.AcquireLockAsync().ConfigureAwait(false);
        try
        {
            entry = new()
            {
                Database = database.Id,
                FromVersion = database.Schema.SchemaVersion,
                ToVersion = database.Schema.SchemaVersion + 1,
                Op = SchemaOp.SetTableSettings,
                Payload = Serializator.Serialize(new SchemaSetTableSettingsPayload
                {
                    TableName = tableName,
                    Settings = new Dictionary<string, string>(settings, StringComparer.Ordinal),
                    RemovedKeys = removedKeys is null ? [] : [.. removedKeys]
                })
            };
            SchemaDeltaApplier.ValidateSchemaDelta(database, entry);
        }
        finally
        {
            database.Schema.ReleaseLock();
        }

        await publisher.ReplicateAndWaitLocalApplyAsync(database, entry).ConfigureAwait(false);
    }

    /// <summary>
    /// Proposes a <see cref="SchemaOp.SetComment"/> delta and replicates it, so every node's
    /// in-memory schema carries the new comment and the KV checkpoint is rewritten. Advances the
    /// database schema version but not <see cref="TableSchema.Version"/>. Cluster mode only —
    /// standalone goes through <see cref="SetTableCommentAsync"/>.
    ///
    /// <para><paramref name="comment"/> is null to remove the comment; the empty string stores a
    /// present-but-empty one.</para>
    /// </summary>
    /// <summary>Whether a non-materialized view with this name currently exists.</summary>
    public static bool ViewExists(DatabaseDescriptor database, string viewName)
        => database.Schema.Views.ContainsKey(viewName);

    /// <summary>
    /// Proposes a <see cref="SchemaOp.CreateView"/> (or <see cref="SchemaOp.ReplaceView"/>) delta and
    /// waits for it to apply locally. The view id is allocated by the caller and carried in the
    /// payload so every node assigns the same one.
    /// </summary>
    /// <remarks>
    /// The name-availability check runs <b>under the schema lock, here</b>, in the same critical
    /// section that builds the delta — not in the caller. Checking outside the lock would be a
    /// check-then-act that two concurrent creations both pass.
    /// </remarks>
    public async Task CreateViewAsync(
        DatabaseDescriptor database,
        string viewId,
        string viewName,
        ViewDefinition definition,
        string? comment,
        bool replace)
    {
        SchemaChangeLogEntry entry;

        await database.Schema.AcquireLockAsync().ConfigureAwait(false);
        try
        {
            if (replace)
            {
                if (!database.Schema.Views.ContainsKey(viewName))
                    throw new CamusDBException(
                        CamusDBErrorCodes.ViewDoesntExist,
                        $"View '{viewName}' does not exist");
            }
            else
            {
                database.Schema.RequireRelationNameAvailable(viewName);
            }

            entry = new()
            {
                Database = database.Id,
                FromVersion = database.Schema.SchemaVersion,
                ToVersion = database.Schema.SchemaVersion + 1,
                Op = replace ? SchemaOp.ReplaceView : SchemaOp.CreateView,
                Payload = Serializator.Serialize(new SchemaViewPayload
                {
                    ViewId = viewId,
                    ViewName = viewName,
                    Definition = definition,
                    Comment = comment
                })
            };
            SchemaDeltaApplier.ValidateSchemaDelta(database, entry);
        }
        finally
        {
            database.Schema.ReleaseLock();
        }

        await publisher.ReplicateAndWaitLocalApplyAsync(database, entry).ConfigureAwait(false);
    }

    /// <summary>Proposes a <see cref="SchemaOp.DropView"/> delta and waits for it to apply locally.</summary>
    public async Task DropViewAsync(DatabaseDescriptor database, string viewName)
    {
        SchemaChangeLogEntry entry;

        await database.Schema.AcquireLockAsync().ConfigureAwait(false);
        try
        {
            if (!database.Schema.Views.ContainsKey(viewName))
                throw new CamusDBException(CamusDBErrorCodes.ViewDoesntExist, $"View '{viewName}' does not exist");

            entry = new()
            {
                Database = database.Id,
                FromVersion = database.Schema.SchemaVersion,
                ToVersion = database.Schema.SchemaVersion + 1,
                Op = SchemaOp.DropView,
                Payload = Serializator.Serialize(new SchemaDropViewPayload { ViewName = viewName })
            };
            SchemaDeltaApplier.ValidateSchemaDelta(database, entry);
        }
        finally
        {
            database.Schema.ReleaseLock();
        }

        await publisher.ReplicateAndWaitLocalApplyAsync(database, entry).ConfigureAwait(false);
    }

    /// <summary>Proposes a <see cref="SchemaOp.RenameView"/> delta and waits for it to apply locally.</summary>
    public async Task RenameViewAsync(
        DatabaseDescriptor database, string viewName, string newName,
        Dictionary<string, ViewDefinition>? dependentViews = null)
    {
        SchemaChangeLogEntry entry;

        await database.Schema.AcquireLockAsync().ConfigureAwait(false);
        try
        {
            if (!database.Schema.Views.ContainsKey(viewName))
                throw new CamusDBException(CamusDBErrorCodes.ViewDoesntExist, $"View '{viewName}' does not exist");

            database.Schema.RequireRelationNameAvailable(newName);

            entry = new()
            {
                Database = database.Id,
                FromVersion = database.Schema.SchemaVersion,
                ToVersion = database.Schema.SchemaVersion + 1,
                Op = SchemaOp.RenameView,
                Payload = Serializator.Serialize(new SchemaRenamePayload
                {
                    TableName = viewName,
                    Kind = SchemaRenameKind.View,
                    NewName = newName,
                    DependentViewDefinitions = dependentViews
                })
            };
            SchemaDeltaApplier.ValidateSchemaDelta(database, entry);
        }
        finally
        {
            database.Schema.ReleaseLock();
        }

        await publisher.ReplicateAndWaitLocalApplyAsync(database, entry).ConfigureAwait(false);
    }

    /// <summary>
    /// Proposes a <see cref="SchemaOp.SetViewDefinition"/> delta: overwrites one view's stored body
    /// without the user having issued a <c>CREATE OR REPLACE</c>. Used by the dependent-view rewrite
    /// that follows a base table or column rename.
    /// </summary>
    public async Task SetViewDefinitionAsync(DatabaseDescriptor database, string viewName, ViewDefinition definition)
    {
        SchemaChangeLogEntry entry;

        await database.Schema.AcquireLockAsync().ConfigureAwait(false);
        try
        {
            entry = new()
            {
                Database = database.Id,
                FromVersion = database.Schema.SchemaVersion,
                ToVersion = database.Schema.SchemaVersion + 1,
                Op = SchemaOp.SetViewDefinition,
                Payload = Serializator.Serialize(new SchemaSetViewDefinitionPayload
                {
                    ViewName = viewName,
                    Definition = definition
                })
            };
            SchemaDeltaApplier.ValidateSchemaDelta(database, entry);
        }
        finally
        {
            database.Schema.ReleaseLock();
        }

        await publisher.ReplicateAndWaitLocalApplyAsync(database, entry).ConfigureAwait(false);
    }

    /// <summary>
    /// Proposes a <see cref="SchemaOp.SetMaterializedViewState"/> delta recording a refresh outcome.
    ///
    /// <para>When <paramref name="swapToTableId"/> is given this is the <b>swap</b> half of a
    /// build-and-swap refresh: the materialized view adopts the freshly built key-space in one
    /// replicated change, so no node ever observes a half-built materialized view and no reader is
    /// blocked while the rebuild runs. Passing null instead only updates the flags.</para>
    /// </summary>
    /// <param name="tableId">The materialized view's own relation id. It is unchanged by a swap —
    /// only the storage it addresses moves — so this identifies the view in both cases.</param>
    /// <param name="publishHlc">When this change is being made — not when the rebuild read its
    /// source. It becomes the entry timestamp, and with it the <c>DroppedAt</c> of the storage the
    /// swap retires, so that storage gets its full retention window starting from the moment it
    /// actually stopped being read.</param>
    public async Task SetMaterializedViewStateAsync(
        DatabaseDescriptor database,
        string tableId,
        bool isPopulated,
        HLCTimestamp? refreshedAt,
        string? swapToTableId = null,
        HLCTimestamp publishHlc = default,
        long? expectedMetadataGeneration = null)
    {
        SchemaChangeLogEntry entry;

        await database.Schema.AcquireLockAsync().ConfigureAwait(false);
        try
        {
            entry = new()
            {
                Ts = publishHlc,
                Database = database.Id,
                FromVersion = database.Schema.SchemaVersion,
                ToVersion = database.Schema.SchemaVersion + 1,
                Op = SchemaOp.SetMaterializedViewState,
                Payload = Serializator.Serialize(new SchemaSetMatViewStatePayload
                {
                    TableId = tableId,
                    IsPopulated = isPopulated,
                    RefreshedAt = refreshedAt,
                    SwapToTableId = swapToTableId,
                    ExpectedMetadataGeneration = expectedMetadataGeneration
                })
            };
            SchemaDeltaApplier.ValidateSchemaDelta(database, entry);
        }
        finally
        {
            database.Schema.ReleaseLock();
        }

        await publisher.ReplicateAndWaitLocalApplyAsync(database, entry).ConfigureAwait(false);
    }

    /// <summary>
    /// Proposes the contents swap that empties <paramref name="tableName"/> and waits until this node
    /// has applied it, then persists the checkpoint that makes the retired generation recoverable.
    /// </summary>
    /// <remarks>
    /// <para>Every value the delta carries is minted by the caller, before this is called and after it
    /// holds the exclusive fence over the old row key-space. That ordering is what makes
    /// <paramref name="contentsValidFrom"/> a real linearization cut: no write into the old generation
    /// can commit on the far side of it.</para>
    ///
    /// <para>Returns nothing on purpose. Once the schema entry commits the truncate has happened
    /// cluster-wide and cannot be undone; a caller that treated a later local failure as "it did not
    /// happen" would be wrong. The caller confirms the outcome by reading the applied storage id.</para>
    /// </remarks>
    public async Task TruncateTableContentsAsync(
        DatabaseDescriptor database,
        string tableId,
        string tableName,
        string expectedStorageId,
        long expectedContentsGeneration,
        string newStorageId,
        HLCTimestamp contentsValidFrom,
        string[] retiredIndexIds,
        string[] newIndexIds)
    {
        SchemaChangeLogEntry entry;

        await database.Schema.AcquireLockAsync().ConfigureAwait(false);
        try
        {
            entry = new()
            {
                Ts = contentsValidFrom,
                Database = database.Id,
                FromVersion = database.Schema.SchemaVersion,
                ToVersion = database.Schema.SchemaVersion + 1,
                Op = SchemaOp.TruncateTable,
                Payload = Serializator.Serialize(new SchemaTruncateTablePayload
                {
                    TableId = tableId,
                    TableName = tableName,
                    ExpectedStorageId = expectedStorageId,
                    ExpectedContentsGeneration = expectedContentsGeneration,
                    NewStorageId = newStorageId,
                    ContentsValidFrom = contentsValidFrom,
                    RetiredIndexIds = retiredIndexIds,
                    NewIndexIds = newIndexIds,
                })
            };
            SchemaDeltaApplier.ValidateSchemaDelta(database, entry);
        }
        finally
        {
            database.Schema.ReleaseLock();
        }

        await publisher.ReplicateAndWaitLocalApplyAsync(database, entry).ConfigureAwait(false);
    }

    public async Task ReplicateSetCommentAsync(
        DatabaseDescriptor database,
        string tableName,
        CommentTarget target,
        string? elementName,
        string? comment)
    {
        SchemaChangeLogEntry entry;

        await database.Schema.AcquireLockAsync().ConfigureAwait(false);
        try
        {
            entry = new()
            {
                Database = database.Id,
                FromVersion = database.Schema.SchemaVersion,
                ToVersion = database.Schema.SchemaVersion + 1,
                Op = SchemaOp.SetComment,
                Payload = Serializator.Serialize(new SchemaSetCommentPayload
                {
                    TableName = tableName,
                    Target = target,
                    ElementName = elementName,
                    Comment = comment
                })
            };
            SchemaDeltaApplier.ValidateSchemaDelta(database, entry);
        }
        finally
        {
            database.Schema.ReleaseLock();
        }

        await publisher.ReplicateAndWaitLocalApplyAsync(database, entry).ConfigureAwait(false);
    }

    /// <summary>
    /// Proposes an <c>AddCheckConstraint</c> delta and replicates it to all cluster nodes.
    /// The proposer must already have validated the expression and confirmed existing rows pass.
    /// Only valid when <c>isClusterMode</c>; standalone nodes apply the change directly.
    /// </summary>
    public async Task ReplicateAddCheckConstraintAsync(
        DatabaseDescriptor database,
        string tableName,
        string constraintName,
        string expression,
        string[] referencedColumns)
    {
        SchemaChangeLogEntry entry;

        await database.Schema.AcquireLockAsync().ConfigureAwait(false);
        try
        {
            entry = new()
            {
                Database = database.Id,
                FromVersion = database.Schema.SchemaVersion,
                ToVersion = database.Schema.SchemaVersion + 1,
                Op = SchemaOp.AddCheckConstraint,
                Payload = Serializator.Serialize(new SchemaCheckConstraintPayload
                {
                    TableName = tableName,
                    ConstraintName = constraintName,
                    Expression = expression,
                    ReferencedColumns = referencedColumns
                })
            };
            SchemaDeltaApplier.ValidateSchemaDelta(database, entry);
        }
        finally
        {
            database.Schema.ReleaseLock();
        }

        await publisher.ReplicateAndWaitLocalApplyAsync(database, entry).ConfigureAwait(false);
    }

    /// <summary>
    /// Proposes a <c>DropCheckConstraint</c> delta and replicates it to all cluster nodes.
    /// Idempotent: if the constraint is already absent, the delta is a no-op but still advances
    /// the schema version.
    /// Only valid when <c>isClusterMode</c>; standalone nodes apply the change directly.
    /// </summary>
    public async Task ReplicateDropCheckConstraintAsync(
        DatabaseDescriptor database,
        string tableName,
        string constraintName)
    {
        SchemaChangeLogEntry entry;

        await database.Schema.AcquireLockAsync().ConfigureAwait(false);
        try
        {
            entry = new()
            {
                Database = database.Id,
                FromVersion = database.Schema.SchemaVersion,
                ToVersion = database.Schema.SchemaVersion + 1,
                Op = SchemaOp.DropCheckConstraint,
                Payload = Serializator.Serialize(new SchemaCheckConstraintPayload
                {
                    TableName = tableName,
                    ConstraintName = constraintName,
                    Expression = "",
                    ReferencedColumns = []
                })
            };
            SchemaDeltaApplier.ValidateSchemaDelta(database, entry);
        }
        finally
        {
            database.Schema.ReleaseLock();
        }

        await publisher.ReplicateAndWaitLocalApplyAsync(database, entry).ConfigureAwait(false);
    }

    /// <summary>
    /// Proposes a <c>SetColumnNotNull</c> delta and replicates it to all cluster nodes.
    /// Idempotent: if the column's NOT NULL state already matches, the delta is a no-op but still
    /// advances the schema version.
    /// Only valid when <c>isClusterMode</c>; standalone nodes apply the change directly.
    /// </summary>
    public async Task ReplicateSetColumnNotNullAsync(
        DatabaseDescriptor database,
        string tableName,
        string columnName,
        bool notNull,
        string? constraintName)
    {
        SchemaChangeLogEntry entry;

        await database.Schema.AcquireLockAsync().ConfigureAwait(false);
        try
        {
            entry = new()
            {
                Database = database.Id,
                FromVersion = database.Schema.SchemaVersion,
                ToVersion = database.Schema.SchemaVersion + 1,
                Op = SchemaOp.SetColumnNotNull,
                Payload = Serializator.Serialize(new SchemaSetColumnNotNullPayload
                {
                    TableName = tableName,
                    ColumnName = columnName,
                    NotNull = notNull,
                    ConstraintName = constraintName
                })
            };
            SchemaDeltaApplier.ValidateSchemaDelta(database, entry);
        }
        finally
        {
            database.Schema.ReleaseLock();
        }

        await publisher.ReplicateAndWaitLocalApplyAsync(database, entry).ConfigureAwait(false);
    }

    // -----------------------------------------------------------------------
    // Schema persistence
    // -----------------------------------------------------------------------

    // Persisting one catalog object is delegated to SchemaMetaStore, which owns the pairing of
    // every object write with the schema-version bump and the "never under the schema lock"
    // assertion. These entry points exist because callers across the engine hold a CatalogsManager,
    // not the store.

    public async Task PersistMetaAsync(DatabaseDescriptor database, KvTransaction tx)
        => await SchemaMetaStore.PersistMetaAsync(database, tx).ConfigureAwait(false);

    public async Task PersistSystemMetaAsync(DatabaseDescriptor database, KvTransaction tx)
        => await SchemaMetaStore.PersistSystemMetaAsync(database, tx).ConfigureAwait(false);

    public async Task PersistSchemaViewAsync(DatabaseDescriptor database, ViewSchema viewSchema, KvTransaction tx)
        => await SchemaMetaStore.PersistSchemaViewAsync(database, viewSchema, tx).ConfigureAwait(false);

    public async Task DeleteSchemaViewAsync(DatabaseDescriptor database, string viewId, KvTransaction tx)
        => await SchemaMetaStore.DeleteSchemaViewAsync(database, viewId, tx).ConfigureAwait(false);

    public async Task PersistSchemaTableAsync(DatabaseDescriptor database, TableSchema tableSchema, KvTransaction tx)
        => await SchemaMetaStore.PersistSchemaTableAsync(database, tableSchema, tx).ConfigureAwait(false);

    public async Task PersistSchemaTableAsync(DatabaseDescriptor database, TableSchema tableSchema, long schemaVersion, KvTransaction tx)
        => await SchemaMetaStore.PersistSchemaTableAsync(database, tableSchema, schemaVersion, tx).ConfigureAwait(false);

    public async Task PersistDroppedTableAsync(DatabaseDescriptor database, string tableId, KvTransaction tx)
        => await SchemaMetaStore.PersistDroppedTableAsync(database, tableId, tx).ConfigureAwait(false);

    public Task PersistDroppedTableAsync(DatabaseDescriptor database, string tableId, long schemaVersion, KvTransaction tx)
        => SchemaMetaStore.PersistDroppedTableAsync(database, tableId, schemaVersion, tx);

    public async Task PersistDroppedTableAsync(
        DatabaseDescriptor database, string tableId, long schemaVersion, KvTransaction tx,
        bool deferred, string formerName, HLCTimestamp droppedAt)
        => await SchemaMetaStore.PersistDroppedTableAsync(
            database, tableId, schemaVersion, tx, deferred, formerName, droppedAt).ConfigureAwait(false);

    /// <summary>
    /// Loads <c>Schema.Tables</c>, <c>Schema.Views</c> and <c>SystemSchema</c> from KV into the
    /// in-memory descriptor. See <see cref="SchemaLoader"/> for the ordering rules this obeys.
    /// </summary>
    public async Task LoadMetaAsync(DatabaseDescriptor database)
        => await SchemaLoader.LoadMetaAsync(database, logger).ConfigureAwait(false);

    internal static SchemaCheckpoint LoadSchemaCheckpoint(ReadOnlySpan<byte> buffer)
        => SchemaLoader.LoadSchemaCheckpoint(buffer);

    /// <summary>
    /// Copies the source database's metadata namespace into the branch's namespace, as-of
    /// <paramref name="forkT"/>. See <see cref="BranchMetaCopier"/> for the snapshot and locking
    /// contract the caller must satisfy.
    /// </summary>
    public async Task CopyMetaForBranchAsync(DatabaseDescriptor source, string branchDbId, HLCTimestamp forkT)
        => await BranchMetaCopier.CopyMetaForBranchAsync(source, branchDbId, forkT).ConfigureAwait(false);


    /// <summary>
    /// Re-persists the complete in-memory schema in a single transaction. Called after log replay
    /// completes, to bring the on-disk checkpoint up to the committed head.
    /// </summary>
    public async Task PersistFullSchemaCheckpointAsync(DatabaseDescriptor database)
        => await checkpoints.PersistFullSchemaCheckpointAsync(database).ConfigureAwait(false);

    // -----------------------------------------------------------------------
    // Delta application
    // -----------------------------------------------------------------------
    //
    // The deltas themselves live under Catalogs/Apply/, which by construction cannot reach KV:
    // apply runs inside the schema partition's commit pipeline, and a write from there re-enters
    // the same partition and deadlocks it. These forwarders exist for the callers that hold a
    // CatalogsManager rather than the appliers.

    public static TableSchema? ApplySchemaDelta(Schema schema, SchemaChangeLogEntry entry)
        => SchemaDeltaApplier.ApplySchemaDelta(schema, entry);

    public static TableSchema? ApplySchemaDelta(Schema schema, DatabaseDescriptor database, SchemaChangeLogEntry entry)
        => SchemaDeltaApplier.ApplySchemaDelta(schema, database, entry);

    /// <summary>
    /// Rebuilds the parsed condition tree of every CHECK constraint whose tree is not built yet.
    /// Only the expression text is persisted, so this must run after a load and after an apply.
    /// </summary>
    internal static void ParseCheckConstraintAsts(TableSchema tableSchema)
        => ConstraintDeltaApplier.ParseCheckConstraintAsts(tableSchema);

    /// <summary>
    /// Records, in memory only, that a committed delta replaced a relation's contents and left a
    /// key-space nothing else names. Called from the apply pipeline, so it must never write KV.
    /// </summary>
    internal static void CaptureContentsRetirementIntent(DatabaseDescriptor database, SchemaChangeLogEntry entry)
        => ContentsRetirementStore.CaptureContentsRetirementIntent(database, entry);

    /// <summary>
    /// Reads every index key-space id a relation's storage generation ever owned. Called by the
    /// proposer, never from apply — the result is frozen into the schema-log payload.
    /// </summary>
    internal async Task<string[]> ReadStorageIndexCatalogAsync(DatabaseDescriptor database, TableSchema tableSchema)
        => await ContentsRetirementStore.ReadStorageIndexCatalogAsync(database, tableSchema).ConfigureAwait(false);

    // -----------------------------------------------------------------------
    // Per-object record stores
    // -----------------------------------------------------------------------
    //
    // Three small key families, each owned by its own store: the orphan record of a deferred-dropped
    // relation, the resumable schema-change coordinator job, and the in-flight materialized-view
    // refresh job. These entry points exist because callers across the engine hold a CatalogsManager
    // rather than the stores.

    public async Task DeleteTableOrphanAsync(DatabaseDescriptor database, string tableId, KvTransaction tx)
        => await OrphanTableStore.DeleteTableOrphanAsync(database, tableId, tx).ConfigureAwait(false);

    public async Task<OrphanTableRecord?> TryGetTableOrphanAsync(DatabaseDescriptor database, string tableId)
        => await OrphanTableStore.TryGetTableOrphanAsync(database, tableId).ConfigureAwait(false);

    public async Task<List<OrphanTableRecord>> LoadTableOrphansAsync(DatabaseDescriptor database)
        => await OrphanTableStore.LoadTableOrphansAsync(database).ConfigureAwait(false);

    public async Task PersistCoordinatorJobAsync(DatabaseDescriptor database, PersistedCoordinatorJob job)
        => await CoordinatorJobStore.PersistCoordinatorJobAsync(database, job).ConfigureAwait(false);

    public async Task DeleteCoordinatorJobAsync(DatabaseDescriptor database, string tableId, string elementName)
        => await CoordinatorJobStore.DeleteCoordinatorJobAsync(database, tableId, elementName).ConfigureAwait(false);

    public async Task DeleteCoordinatorJobsForTableAsync(
        DatabaseDescriptor database,
        string tableId,
        KvTransaction tx)
        => await CoordinatorJobStore.DeleteCoordinatorJobsForTableAsync(database, tableId, tx).ConfigureAwait(false);

    public async Task<List<PersistedCoordinatorJob>> LoadCoordinatorJobsAsync(DatabaseDescriptor database)
        => await CoordinatorJobStore.LoadCoordinatorJobsAsync(database).ConfigureAwait(false);

    public async Task PersistRefreshJobAsync(DatabaseDescriptor database, MaterializedViewRefreshJob job)
        => await MaterializedViewRefreshJobStore.PersistRefreshJobAsync(database, job).ConfigureAwait(false);

    public async Task DeleteRefreshJobAsync(DatabaseDescriptor database, string viewTableId)
        => await MaterializedViewRefreshJobStore.DeleteRefreshJobAsync(database, viewTableId).ConfigureAwait(false);

    public async Task<MaterializedViewRefreshJob?> TryGetRefreshJobAsync(DatabaseDescriptor database, string viewTableId)
        => await MaterializedViewRefreshJobStore.TryGetRefreshJobAsync(database, viewTableId).ConfigureAwait(false);

    public Task<List<MaterializedViewRefreshJob>> ListRefreshJobsAsync(DatabaseDescriptor database)
        => MaterializedViewRefreshJobStore.ListRefreshJobsAsync(database);

    /// <summary>
    /// The listing by database id, for callers that do not have the database open — the background
    /// sweep asks "is there anything to reclaim here" without opening every database on every tick.
    /// </summary>
    public static async Task<List<MaterializedViewRefreshJob>> ListRefreshJobsAsync(IKahuna kahuna, string dbId)
        => await MaterializedViewRefreshJobStore.ListRefreshJobsAsync(kahuna, dbId).ConfigureAwait(false);

    /// <summary>
    /// Standalone-mode counterpart of <see cref="ReplicateSetCommentAsync"/>: mutates the in-memory
    /// schema and rewrites the table blob directly, with no schema-log entry. It rides the blob without
    /// bumping <see cref="TableSchema.Version"/>, and does not advance the database schema version
    /// either; only the replicated path does.
    ///
    /// <para><b>Known divergence between the modes.</b> The same statement advances the database schema
    /// version in cluster mode (its delta lands in the central apply) and not here. Nothing currently
    /// keys off the version for comments, so this is latent rather than broken — but it is the same
    /// shape of bug that made table settings invisible to background sweeps, and the fix is the same:
    /// propose the delta in both modes rather than shortcutting one.</para>
    ///
    /// <para>Ordering matters and is not incidental: the mutation must happen before the persist
    /// (which serializes the in-memory schema), the schema lock must be released before the persist
    /// (no replicated write may run under it), and a failed persist/commit must roll the in-memory
    /// value back so memory never runs ahead of what is durable.</para>
    ///
    /// <para>Returns the previous comment's presence so the caller can tell a genuine change from a
    /// no-op; a null <paramref name="comment"/> removes the comment.</para>
    /// </summary>
    public async Task SetTableCommentAsync(
        DatabaseDescriptor database,
        TableDescriptor table,
        CommentTarget target,
        string? elementName,
        string? comment)
    {
        KvTransaction tx = await database.Transactions.BeginAsync(
            CamusIsolationLevel.ReadCommitted, CamusTransactionMode.ReadWrite
        ).ConfigureAwait(false);

        TableSchema? revertSnapshot = null;
        bool mutated = false;
        try
        {
            await database.Schema.AcquireLockAsync().ConfigureAwait(false);
            try
            {
                revertSnapshot = CaptureCommentState(table.Schema, target, elementName);

                ApplyCommentToSchema(table.Schema, target, elementName, comment);
                mutated = true;
            }
            finally
            {
                database.Schema.ReleaseLock();
            }

            await PersistSchemaTableAsync(database, table.Schema, tx).ConfigureAwait(false);
            await database.Transactions.CommitAsync(tx).ConfigureAwait(false);
            mutated = false;
        }
        finally
        {
            if (mutated && revertSnapshot is not null)
            {
                await database.Schema.AcquireLockAsync().ConfigureAwait(false);
                try { RestoreCommentState(table.Schema, target, elementName, revertSnapshot); }
                finally { database.Schema.ReleaseLock(); }
            }
            await database.Transactions.RollbackIfNotCompletedAsync(tx).ConfigureAwait(false);
        }
    }

    /// <summary>
    /// Captures just enough of <paramref name="tableSchema"/> to undo a comment mutation: the prior
    /// comment value for the targeted element, carried on a throwaway <see cref="TableSchema"/> so
    /// the revert path needs no extra type.
    /// </summary>
    private static TableSchema CaptureCommentState(TableSchema tableSchema, CommentTarget target, string? elementName)
    {
        TableSchema snapshot = new();

        switch (target)
        {
            case CommentTarget.Table:
                snapshot.Comment = tableSchema.Comment;
                break;

            case CommentTarget.Column:
                {
                    TableColumnSchema? col = tableSchema.Columns?.FirstOrDefault(
                        c => string.Equals(c.Name, elementName, StringComparison.OrdinalIgnoreCase));
                    snapshot.Comment = col?.Comment;
                    break;
                }

            case CommentTarget.Index:
                {
                    TableIndexSchema? ix = tableSchema.Indexes?.FirstOrDefault(
                        i => string.Equals(i.Name, elementName, StringComparison.OrdinalIgnoreCase));
                    snapshot.Comment = ix?.Comment;
                    break;
                }
        }

        return snapshot;
    }

    private static void RestoreCommentState(TableSchema tableSchema, CommentTarget target, string? elementName, TableSchema snapshot)
        => ApplyCommentToSchema(tableSchema, target, elementName, snapshot.Comment);

    /// <summary>
    /// The single in-memory comment mutation, shared by the standalone write path and its revert so
    /// the two can never drift. Mirrors <c>TableDeltaApplier.ApplySetComment</c>, which does the same work on the
    /// replicated path.
    /// </summary>
    private static void ApplyCommentToSchema(TableSchema tableSchema, CommentTarget target, string? elementName, string? comment)
    {
        switch (target)
        {
            case CommentTarget.Table:
                tableSchema.Comment = comment;
                break;

            case CommentTarget.Column:
                {
                    int idx = tableSchema.Columns?.FindIndex(
                        c => string.Equals(c.Name, elementName, StringComparison.OrdinalIgnoreCase)) ?? -1;

                    if (idx < 0)
                        break;

                    TableColumnSchema old = tableSchema.Columns![idx];
                    tableSchema.Columns[idx] = new TableColumnSchema(
                        id: old.Id,
                        name: old.Name,
                        type: old.Type,
                        notNull: old.NotNull,
                        defaultValue: old.DefaultValue,
                        state: old.State,
                        maxLength: old.MaxLength,
                        arrayElementType: old.ArrayElementType,
                        defaultFunction: old.DefaultFunction,
                        notNullConstraintName: old.NotNullConstraintName,
                        comment: comment
                    );
                    break;
                }

            case CommentTarget.Index:
                {
                    int idx = tableSchema.Indexes?.FindIndex(
                        i => string.Equals(i.Name, elementName, StringComparison.OrdinalIgnoreCase)) ?? -1;

                    if (idx < 0)
                        break;

                    TableIndexSchema old = tableSchema.Indexes![idx];
                    tableSchema.Indexes[idx] = new TableIndexSchema(
                        id: old.Id,
                        name: old.Name,
                        columnIds: old.ColumnIds,
                        type: old.Type,
                        state: old.State,
                        startOffset: old.StartOffset,
                        columnDirections: old.ColumnDirections,
                        includeColumnIds: old.IncludeColumnIds,
                        comment: comment
                    );
                    break;
                }
        }
    }

}
