
/**
 * This file is part of CamusDB
 *
 * For the full copyright and license information, please view the LICENSE.txt
 * file that was distributed with this source code.
 */

using CamusDB.Core.Catalogs.Apply;
using CamusDB.Core.Catalogs.Meta;
using CamusDB.Core.Catalogs.Models;
using CamusDB.Core.Catalogs.Replication;
using CamusDB.Core.CommandsExecutor.Models;
using CamusDB.Core.CommandsExecutor.Models.Tickets;
using CamusDB.Core.Serializer;
using CamusDB.Core.Transactions;
using Kahuna;
using Kommander.Time;

namespace CamusDB.Core.Catalogs;

/// <summary>
/// Creates, alters, drops, renames, relinks and truncates a relation. Every operation here is a
/// replicated schema change: it builds a delta, validates it under the schema lock, releases the
/// lock, and hands the delta to <see cref="SchemaChangePublisher"/>.
///
/// <para><b>A relation is identified by an immutable id, never by its name.</b> Rows, index entries
/// and stored view bodies all resolve through that id, which is what makes a rename metadata-only
/// and what lets a relink re-attach a detached key-space under a different name.</para>
///
/// <para><b>Relink and truncate separate a relation's identity from its contents.</b> The identity
/// survives; the key-space is replaced. The generation that is left behind is named by nothing in
/// the schema afterwards, so <see cref="ContentsRetirementStore"/> records it — otherwise its rows
/// are unreachable rather than deleted.</para>
///
/// <para><b><see cref="RegisterTableSystemObject"/> takes a different lock on purpose.</b> It holds
/// <c>SystemSchemaSemaphore</c>, not <c>Schema.Semaphore</c>: it maintains the legacy system-schema
/// index map rather than the replicated schema, and folding it into the schema-lock discipline would
/// serialize it against DDL it has no relationship with.</para>
/// </summary>
internal sealed class RelationCatalog
{
    private readonly SchemaChangePublisher publisher;

    public RelationCatalog(SchemaChangePublisher publisher)
    {
        ArgumentNullException.ThrowIfNull(publisher);

        this.publisher = publisher;
    }

    /// <summary>
    /// Adds a new table object to the database schema as well as its indexes.
    /// <paramref name="tableId"/> is the pre-allocated, globally-unique id for the new table,
    /// produced by the proposer via <see cref="DatabaseRegistry.AllocateTableIdAsync"/> before
    /// this method is called. It is carried verbatim in the replicated payload so every node
    /// applies the same id; the caller is responsible for ensuring it was not generated by
    /// a follower.
    /// </summary>
    /// <exception cref="CamusDBException"></exception>
    internal Task<TableSchema> CreateTable(DatabaseDescriptor database, CreateTableTicket ticket, KvTransaction tx, string tableId)
        => CreateTableReplicatedAsync(database, ticket, tx, tableId);

    /// <summary>
    /// Modifies an existing table object allowing to add or remove columns.
    /// </summary>
    /// <param name="database"></param>
    /// <param name="ticket"></param>
    /// <returns></returns>
    /// <exception cref="CamusDBException"></exception>
    internal Task<TableSchema> AlterTable(DatabaseDescriptor database, AlterColumnTicket ticket, KvTransaction tx)
        => AlterTableReplicatedAsync(database, ticket, tx);

    /// <summary>
    /// Removes a table from the live schema via a replicated <see cref="SchemaOp.DropTable"/> delta.
    /// When <paramref name="deferred"/> is <c>true</c> the drop is recoverable: the schema checkpoint
    /// that deletes the per-table meta key also writes the table's orphan record in the same
    /// transaction (see <see cref="PersistDroppedTableAsync"/>), so a crash can never detach the table
    /// without leaving a recovery record. The caller must have already retained the row/index data.
    /// </summary>
    internal Task<TableSchema?> DropTableSchema(DatabaseDescriptor database, string tableName, string tableId, KvTransaction tx, bool deferred = false)
        => DropTableReplicatedAsync(database, tableName, tx, deferred);

    /// <summary>
    /// Allows querying the current schema of a table object.
    /// </summary>
    /// <param name="database"></param>
    /// <param name="tableName"></param>
    /// <returns></returns>
    /// <exception cref="CamusDBException"></exception>
    internal TableSchema GetTableSchema(DatabaseDescriptor database, string tableName) // @todo return a snapshot instead of the schema
    {
        if (database.Schema.Tables.TryGetValue(tableName, out TableSchema? tableSchema))
            return tableSchema;

        throw new CamusDBException(CamusDBErrorCodes.TableDoesntExist, $"Table '{tableName}' doesn't exist");
    }

    /// <summary>
    /// Returns true if a table exists
    /// </summary>
    /// <param name="database"></param>
    /// <param name="tableName"></param>
    /// <returns></returns>
    internal bool TableExists(DatabaseDescriptor database, string tableName)
    {
        return database.Schema.Tables.ContainsKey(tableName);
    }

    private async Task<TableSchema> CreateTableReplicatedAsync(DatabaseDescriptor database, CreateTableTicket ticket, KvTransaction tx, string tableId)
    {
        SchemaChangeLogEntry entry;

        await database.Schema.AcquireLockAsync().ConfigureAwait(false);
        try
        {
            entry = SchemaChangeEntryFactory.CreateTableEntry(database, ticket, tx, tableId);
            SchemaDeltaApplier.ValidateSchemaDelta(database, entry);
        }
        finally
        {
            database.Schema.ReleaseLock();
        }

        await publisher.ReplicateAndWaitLocalApplyAsync(database, entry).ConfigureAwait(false);
        return GetTableSchema(database, ticket.TableName);
    }

    private async Task<TableSchema> AlterTableReplicatedAsync(DatabaseDescriptor database, AlterColumnTicket ticket, KvTransaction tx)
    {
        SchemaChangeLogEntry entry;

        await database.Schema.AcquireLockAsync().ConfigureAwait(false);
        try
        {
            entry = SchemaChangeEntryFactory.AlterTableEntry(database, ticket, tx);
            SchemaDeltaApplier.ValidateSchemaDelta(database, entry);
        }
        finally
        {
            database.Schema.ReleaseLock();
        }

        await publisher.ReplicateAndWaitLocalApplyAsync(database, entry).ConfigureAwait(false);
        return GetTableSchema(database, ticket.TableName);
    }

    private async Task<TableSchema?> DropTableReplicatedAsync(DatabaseDescriptor database, string tableName, KvTransaction tx, bool deferred)
    {
        SchemaChangeLogEntry entry;

        await database.Schema.AcquireLockAsync().ConfigureAwait(false);
        try
        {
            entry = SchemaChangeEntryFactory.DropTableEntry(database, tableName, tx, deferred);
            SchemaDeltaApplier.ValidateSchemaDelta(database, entry);
        }
        finally
        {
            database.Schema.ReleaseLock();
        }

        await publisher.ReplicateAndWaitLocalApplyAsync(database, entry).ConfigureAwait(false);
        return null;
    }

    /// <summary>
    /// Reattaches an orphaned (deferred-dropped) table to the live schema under <paramref name="newName"/>,
    /// reusing its preserved id so it reads its retained rows and index entries. Modeled as a dedicated
    /// <see cref="SchemaOp.RelinkTable"/> delta rebuilt from the orphan's captured schema — preserving the
    /// original table id, column ids, index definitions, check constraints, <b>and schema version</b> — so
    /// every node reconstructs an identical table and rows written under the drop-time version decode
    /// correctly. The apply configures a lazy schema-history loader against the retained
    /// <c>{dbId}/meta/history:{tableId}:*</c> keys, so rows written under earlier pre-<c>ALTER</c> versions
    /// also decode (immediately and after reopen). The orphan record is removed in the caller's DDL
    /// transaction after the reattach is applied.
    ///
    /// <para><b>Ordering:</b> reattach-then-delete-orphan, mirroring database relink. A crash after the
    /// reattach but before the orphan-record delete commits leaves a live table with a stale orphan
    /// record; the garbage collector skips orphan records whose table exists in the live schema.</para>
    /// </summary>
    internal async Task<TableSchema> RelinkTable(DatabaseDescriptor database, OrphanTableRecord orphan, string newName, KvTransaction tx)
    {
        SchemaChangeLogEntry entry;

        await database.Schema.AcquireLockAsync().ConfigureAwait(false);
        try
        {
            entry = SchemaChangeEntryFactory.RelinkTableEntry(database, orphan, newName, tx);
            SchemaDeltaApplier.ValidateSchemaDelta(database, entry);
        }
        finally
        {
            database.Schema.ReleaseLock();
        }

        await publisher.ReplicateAndWaitLocalApplyAsync(database, entry).ConfigureAwait(false);

        TableSchema reattached = GetTableSchema(database, newName);

        // Restore the system-schema table object and persist it in the DDL transaction, mirroring
        // TableCreator (deferred drop removed it). Without this the live schema has the table but the
        // system schema does not, an asymmetry with the create/drop paths.
        RegisterTableSystemObject(database, reattached);
        await SchemaMetaStore.PersistSystemMetaAsync(database, tx).ConfigureAwait(false);

        // The table is live again — drop the orphan record so the GC leaves the reattached data alone.
        await OrphanTableStore.DeleteTableOrphanAsync(database, orphan.TableId, tx).ConfigureAwait(false);

        return reattached;
    }

    /// <summary>
    /// Publishes a retired contents generation as a <b>new</b> relation, so the rows a
    /// <c>TRUNCATE</c> made unreachable can be read again.
    /// </summary>
    /// <remarks>
    /// <para><b>A fresh logical id is mandatory.</b> The retired key-space is named by a storage id,
    /// and on a relation's first truncate that storage id <em>is</em> the still-live source relation's
    /// id. Reusing it would publish a second relation under an id that is already live — two names for
    /// one identity, with the grants and dependencies of the source silently attached to the recovery.
    /// The recovered relation therefore gets a new id and points at the retired key-space through
    /// <see cref="TableSchema.StorageId"/>, which is exactly the separation that made the truncate
    /// cheap in the first place.</para>
    ///
    /// <para>The captured column layouts are copied under the new id because the retained rows carry
    /// the source relation's schema versions, and the append-only history keys that describe those
    /// versions live under the source's id — where the recovered relation cannot reach them.</para>
    ///
    /// <para>Order is reattach, then delete the record. A crash in between leaves a live relation with
    /// a stale record; the collector recognises that from <see cref="OrphanTableRecord.RelinkTargetId"/>
    /// and removes the record without touching the storage the recovery now owns.</para>
    /// </remarks>
    internal async Task<TableSchema> RelinkRetiredContents(
        DatabaseDescriptor database, OrphanTableRecord orphan, string newTableId, string newName, KvTransaction tx)
    {
        TableSchema captured = orphan.Schema;

        OrphanTableRecord published = new()
        {
            Kind = orphan.Kind,
            TableId = newTableId,
            FormerName = orphan.FormerName,
            DroppedAt = orphan.DroppedAt,
            SourceTableId = orphan.SourceTableId,
            RetiredStorageId = orphan.RetiredStorageId,
            RelinkTargetId = newTableId,
            Schema = new()
            {
                Id = newTableId,
                // The recovered relation reads the retired key-space; its own id names nothing on disk.
                StorageId = orphan.RetiredStorageId,
                Version = captured.Version,
                Name = newName,
                Columns = captured.Columns,
                Indexes = captured.Indexes,
                CheckConstraints = captured.CheckConstraints,
                Settings = captured.Settings,
                Comment = captured.Comment,
                Kind = captured.Kind,
                ViewDefinition = captured.ViewDefinition,
                IsPopulated = captured.IsPopulated,
                RefreshedAt = captured.RefreshedAt,
            }
        };

        SchemaChangeLogEntry entry;

        await database.Schema.AcquireLockAsync().ConfigureAwait(false);
        try
        {
            entry = SchemaChangeEntryFactory.RelinkTableEntry(database, published, newName, tx);
            SchemaDeltaApplier.ValidateSchemaDelta(database, entry);
        }
        finally
        {
            database.Schema.ReleaseLock();
        }

        await publisher.ReplicateAndWaitLocalApplyAsync(database, entry).ConfigureAwait(false);

        TableSchema reattached = GetTableSchema(database, newName);

        RegisterTableSystemObject(database, reattached);
        await SchemaMetaStore.PersistSystemMetaAsync(database, tx).ConfigureAwait(false);

        // Copy the captured layouts under the new id so a row written under an older version of the
        // source relation still decodes through the recovered one.
        IKahuna kahuna = database.Kahuna.Kahuna;
        foreach (TableSchemaHistory history in captured.SchemaHistory ?? [])
        {
            byte[] historyBytes = MetaJsonSerializer.Serialize(history, MetaJsonContext.Default.TableSchemaHistory);
            await MetaKeyWriter.WriteMetaKey(kahuna, tx, MetaKeys.HistoryKey(database.Id, newTableId, history.Version), historyBytes).ConfigureAwait(false);
        }

        // Addressed by the key-space it protected, not by the relation that now owns it.
        await OrphanTableStore.DeleteTableOrphanAsync(database, orphan.RetiredStorageId, tx).ConfigureAwait(false);

        return reattached;
    }

    /// <summary>
    /// Stamps a retired-contents record with the relation a recovery is about to publish, in its own
    /// committed transaction.
    /// </summary>
    /// <remarks>
    /// Written <b>before</b> the relation is published, so a crash between the two leaves evidence.
    /// Without it the collector cannot tell a recovery that half-finished from one that never started,
    /// and would purge the storage the half-finished recovery is about to hand back.
    /// </remarks>
    internal async Task RecordRelinkTargetAsync(DatabaseDescriptor database, OrphanTableRecord orphan, string targetId)
    {
        orphan.RelinkTargetId = targetId;

        byte[] bytes = MetaJsonSerializer.Serialize(orphan, MetaJsonContext.Default.OrphanTableRecord);

        KvTransaction tx = await database.Transactions.BeginAsync(
            CamusIsolationLevel.ReadCommitted, CamusTransactionMode.ReadWrite
        ).ConfigureAwait(false);
        try
        {
            await MetaKeyWriter.WriteMetaKey(database.Kahuna.Kahuna, tx, MetaKeys.OrphanKey(database.Id, orphan.RetiredStorageId), bytes).ConfigureAwait(false);
            await database.Transactions.CommitAsync(tx).ConfigureAwait(false);
        }
        finally
        {
            await database.Transactions.RollbackIfNotCompletedAsync(tx).ConfigureAwait(false);
        }
    }

    /// <summary>
    /// Adds (or re-adds) the system-schema table object for <paramref name="tableSchema"/>, keyed by its
    /// immutable id. Shared by table creation and relink so both keep <c>SystemSchema.Tables</c> in sync
    /// with the live schema. In-memory only; the caller persists via <see cref="PersistSystemMetaAsync"/>.
    /// </summary>
    internal void RegisterTableSystemObject(DatabaseDescriptor database, TableSchema tableSchema)
    {
        database.SystemSchemaSemaphore.Wait();
        try
        {
            database.SystemSchema.Tables.TryAdd(
                tableSchema.Id ?? "",
                new DatabaseTableObject(
                    type: DatabaseObjectType.Table,
                    id: tableSchema.Id ?? "",
                    name: tableSchema.Name!,
                    startOffset: ""));
        }
        finally
        {
            database.SystemSchemaSemaphore.Release();
        }
    }

    private async Task<bool> RenameTableReplicatedAsync(
        DatabaseDescriptor database, RenameTableTicket ticket, KvTransaction tx,
        Dictionary<string, ViewDefinition>? dependentViews)
    {
        SchemaChangeLogEntry entry;

        await database.Schema.AcquireLockAsync().ConfigureAwait(false);
        try
        {
            entry = SchemaChangeEntryFactory.RenameTableEntry(database, ticket, tx, dependentViews);
            SchemaDeltaApplier.ValidateSchemaDelta(database, entry);
        }
        finally
        {
            database.Schema.ReleaseLock();
        }

        await publisher.ReplicateAndWaitLocalApplyAsync(database, entry).ConfigureAwait(false);
        return true;
    }

    /// <param name="dependentViews">
    /// Rewritten bodies for the views that read this relation, applied in the same delta so no node
    /// ever observes a stale body — which, once the old name is free, can resolve to a different
    /// relation rather than fail. Null when nothing depends on it.
    /// </param>
    internal Task<bool> RenameTable(
        DatabaseDescriptor database, RenameTableTicket ticket, KvTransaction tx,
        Dictionary<string, ViewDefinition>? dependentViews = null)
        => RenameTableReplicatedAsync(database, ticket, tx, dependentViews);

    internal async Task<bool> RenameIndexInTableAsync(
        DatabaseDescriptor database,
        AlterIndexTicket ticket,
        KvTransaction tx
    )
    {
        string newName = ticket.NewName ?? throw new CamusDBException(CamusDBErrorCodes.InvalidInput, "NewName is required for RenameIndex");
        SchemaChangeLogEntry entry;

        await database.Schema.AcquireLockAsync().ConfigureAwait(false);
        try
        {
            entry = SchemaChangeEntryFactory.RenameIndexEntry(database, ticket, newName, tx);

            SchemaDeltaApplier.ValidateSchemaDelta(database, entry);
        }
        finally
        {
            database.Schema.ReleaseLock();
        }

        await publisher.ReplicateAndWaitLocalApplyAsync(database, entry).ConfigureAwait(false);
        return true;
    }

    /// <summary>
    /// Proposes the contents swap that empties <paramref name="tableName"/> and waits until this node
    /// has applied it, then persists the checkpoint that makes the retired generation recoverable.
    /// </summary>
    /// <remarks>
    /// <para>Every value the delta carries is minted by the caller, before this is called and after it
    /// holds the exclusive fence over the old row key-space. That ordering is what makes
    /// <paramref name="contentsValidFrom"/> a real linearization cut: no write into the old generation
    /// can commit on the far side of it.</para>
    ///
    /// <para>Returns nothing on purpose. Once the schema entry commits the truncate has happened
    /// cluster-wide and cannot be undone; a caller that treated a later local failure as "it did not
    /// happen" would be wrong. The caller confirms the outcome by reading the applied storage id.</para>
    /// </remarks>
    internal async Task TruncateTableContentsAsync(
        DatabaseDescriptor database,
        string tableId,
        string tableName,
        string expectedStorageId,
        long expectedContentsGeneration,
        string newStorageId,
        HLCTimestamp contentsValidFrom,
        string[] retiredIndexIds,
        string[] newIndexIds)
    {
        SchemaChangeLogEntry entry;

        await database.Schema.AcquireLockAsync().ConfigureAwait(false);
        try
        {
            entry = SchemaChangeEntryFactory.TruncateTableEntry(database, tableId, tableName, expectedStorageId, expectedContentsGeneration, newStorageId, contentsValidFrom, retiredIndexIds, newIndexIds);
            SchemaDeltaApplier.ValidateSchemaDelta(database, entry);
        }
        finally
        {
            database.Schema.ReleaseLock();
        }

        await publisher.ReplicateAndWaitLocalApplyAsync(database, entry).ConfigureAwait(false);
    }
}
