
/**
 * This file is part of CamusDB
 *
 * For the full copyright and license information, please view the LICENSE.txt
 * file that was distributed with this source code.
 */

using System.Collections.Concurrent;
using System.Diagnostics.CodeAnalysis;
using CamusDB.Core.CommandsExecutor.Models;

namespace CamusDB.App.Services;

/// <summary>
/// Short-lived operationId → response cache for idempotent DDL forwarding.
///
/// When a follower forwards a DDL ticket and the leader applies it but the
/// HTTP response is lost in transit, the retry arrives at the leader with the
/// same stable operationId generated by <c>TryForwardDdlAsync</c>.  The leader
/// looks up that id, finds the previously committed response, and replays it —
/// no double-apply.
///
/// Only successful ("ok") responses are cached; error responses are not, so a
/// corrected retry always re-executes.  Entries expire after
/// <see cref="Ttl"/> so the dictionary stays bounded without a background timer.
/// Eviction is lazy: a sweep runs at most once per <see cref="EvictionInterval"/>.
/// </summary>
public sealed class DdlOperationIdCache
{
    internal static readonly TimeSpan Ttl = TimeSpan.FromSeconds(120);
    private static readonly TimeSpan EvictionInterval = TimeSpan.FromSeconds(60);

    private sealed record Entry(SchemaDdlForwardResponse Response, DateTime ExpiresAt);

    private readonly ConcurrentDictionary<string, Entry> cache = new();
    private DateTime lastEviction = DateTime.UtcNow;

    /// <summary>
    /// Returns true and populates <paramref name="response"/> if a non-expired
    /// entry for <paramref name="operationId"/> exists.
    /// </summary>
    public bool TryGet(string operationId, [NotNullWhen(true)] out SchemaDdlForwardResponse? response)
    {
        if (cache.TryGetValue(operationId, out Entry? entry) && entry.ExpiresAt > DateTime.UtcNow)
        {
            response = entry.Response;
            return true;
        }
        response = null;
        return false;
    }

    /// <summary>Stores a successful response keyed by <paramref name="operationId"/>.</summary>
    public void Set(string operationId, SchemaDdlForwardResponse response)
    {
        cache[operationId] = new Entry(response, DateTime.UtcNow + Ttl);
        MaybeEvict();
    }

    private void MaybeEvict()
    {
        DateTime now = DateTime.UtcNow;
        if (now - lastEviction < EvictionInterval)
            return;

        lastEviction = now;
        foreach (string key in cache.Keys.ToArray())
        {
            if (cache.TryGetValue(key, out Entry? e) && e.ExpiresAt <= now)
                cache.TryRemove(key, out _);
        }
    }
}
