name: Run Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:  
  CamusDB-Tests:
    runs-on: "ubuntu-latest"    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
        with:
          fetch-depth: 2
      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      - name: Run Tests
        timeout-minutes: 60
        run: (chmod +x ./scripts/run-tests.sh && ./scripts/run-tests.sh)
