name: Run Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  CamusDB-Tests:
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Install .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore CamusDB.Tests/CamusDB.Tests.csproj

      - name: Build
        run: dotnet build CamusDB.Tests/CamusDB.Tests.csproj --no-restore --configuration Debug

      - name: Run Tests
        timeout-minutes: 60
        run: |
          mkdir -p CamusDB.Tests/bin/Debug/net10.0/Data/
          dotnet test CamusDB.Tests/CamusDB.Tests.csproj \
            --no-build \
            --configuration Debug \
            -v normal \
            --blame-hang \
            --blame-hang-timeout 60s \
            --blame-crash \
            -- NUnit.MaxParallelWorkers=8
